"""Add campaign and challenge models for challenge campaigns system

Revision ID: 11a48d00c6b7
Revises: f252668f8bc3
Create Date: 2025-08-14 14:10:00.060375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a48d00c6b7'
down_revision = 'f252668f8bc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_cadence_hours', sa.Integer(), nullable=False),
    sa.Column('announcement_channels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('release_cadence_hours >= 1 AND release_cadence_hours <= 168', name=op.f('ck_campaigns_ck_campaigns_cadence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('guild_id', 'title', name='uq_campaigns_guild_title')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_campaigns_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_campaigns_guild_id', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_start_time'), ['start_time'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('input_generator_script', sa.Text(), nullable=True),
    sa.Column('solution_validator_script', sa.Text(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_position >= 1', name=op.f('ck_challenges_ck_challenges_position_positive')),
    sa.CheckConstraint('points_value >= 0', name=op.f('ck_challenges_ck_challenges_points_non_negative')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_challenges_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges')),
    sa.UniqueConstraint('campaign_id', 'order_position', name='uq_challenges_campaign_position')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_challenges_campaign_position', ['campaign_id', 'order_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_is_released'), ['is_released'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_order_position'), ['order_position'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_released_at'), ['released_at'], unique=False)

    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('uq_squads_guild_default'), postgresql_where='(is_default = true)')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_squads_guild_default'), ['guild_id'], unique=True, postgresql_where='(is_default = true)')
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)

    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.drop_column('command_metadata')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_released_at'))
        batch_op.drop_index(batch_op.f('ix_challenges_order_position'))
        batch_op.drop_index(batch_op.f('ix_challenges_is_released'))
        batch_op.drop_index('ix_challenges_campaign_position')
        batch_op.drop_index(batch_op.f('ix_challenges_campaign_id'))

    op.drop_table('challenges')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_start_time'))
        batch_op.drop_index(batch_op.f('ix_campaigns_is_active'))
        batch_op.drop_index('ix_campaigns_guild_id')
        batch_op.drop_index('ix_campaigns_guild_active')
        batch_op.drop_index('ix_campaigns_created_by')

    op.drop_table('campaigns')
    # ### end Alembic commands ###