"""Add help_conversations table for conversation tracking

Revision ID: 4f4c4fe587ed
Revises: ee57f629d8da
Create Date: 2025-07-30 11:31:05.326665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4c4fe587ed'
down_revision = 'ee57f629d8da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('context_messages', sa.JSON(), nullable=True),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('retention_policy', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_conversations'))
    )
    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_conversations_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index('ix_help_conversations_guild_started', ['guild_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_is_sensitive'), ['is_sensitive'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_help_conversations_session_started', ['session_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_started_at'), ['started_at'], unique=False)
        batch_op.create_index('ix_help_conversations_tokens_started', ['tokens_used', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_help_conversations_user_started', ['user_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_help_conversations_user_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_user_id'))
        batch_op.drop_index('ix_help_conversations_tokens_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_started_at'))
        batch_op.drop_index('ix_help_conversations_session_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_is_sensitive'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_is_resolved'))
        batch_op.drop_index('ix_help_conversations_guild_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_guild_id'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_channel_id'))

    op.drop_table('help_conversations')
    # ### end Alembic commands ###