"""add quests system

Revision ID: 5e26dbb7a44f
Revises: 5d6e7f8g9h0i
Create Date: 2025-12-19 23:17:30.627754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e26dbb7a44f'
down_revision = '5d6e7f8g9h0i'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('python_script', sa.Text(), nullable=True),
    sa.Column('input_generator_script', sa.Text(), nullable=True),
    sa.Column('solution_validator_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_guild_id'), ['guild_id'], unique=False)

    op.create_table('daily_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_daily_quests_quest_id_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_quests')),
    sa.UniqueConstraint('guild_id', 'quest_id', 'active_date', name='uq_daily_quests_per_day')
    )
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_quests_active_date'), ['active_date'], unique=False)
        batch_op.create_index('ix_daily_quests_guild_date', ['guild_id', 'active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_quest_id'), ['quest_id'], unique=False)

    op.create_table('quest_progress',
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_progress_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_quest_id', 'user_id', name=op.f('pk_quest_progress'))
    )
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_progress_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index('ix_quest_progress_guild_user', ['guild_id', 'user_id'], unique=False)

    with op.batch_alter_table('attachment_filter_configs', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('ignored_extensions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('warn_extensions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('forum_agents', schema=None) as batch_op:
        batch_op.alter_column('enable_user_tagging',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('enable_responses',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('notification_topics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_enable_responses'), ['enable_responses'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_enable_user_tagging'), ['enable_user_tagging'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_agents_enable_user_tagging'))
        batch_op.drop_index(batch_op.f('ix_forum_agents_enable_responses'))
        batch_op.alter_column('notification_topics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
        batch_op.alter_column('enable_responses',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
        batch_op.alter_column('enable_user_tagging',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)

    with op.batch_alter_table('attachment_filter_configs', schema=None) as batch_op:
        batch_op.alter_column('warn_extensions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
        batch_op.alter_column('ignored_extensions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)

    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_quest_progress_guild_user')
        batch_op.drop_index(batch_op.f('ix_quest_progress_guild_id'))

    op.drop_table('quest_progress')
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_quests_quest_id'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_is_active'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_guild_id'))
        batch_op.drop_index('ix_daily_quests_guild_date')
        batch_op.drop_index(batch_op.f('ix_daily_quests_active_date'))

    op.drop_table('daily_quests')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_guild_id'))

    op.drop_table('quests')
    # ### end Alembic commands ###