"""Add points_earned field to challenge_submissions

Revision ID: 9e3841cb0b06
Revises: 80956826a0eb
Create Date: 2025-08-14 18:06:38.495363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3841cb0b06'
down_revision = '80956826a0eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.drop_column('points_earned')

    # ### end Alembic commands ###