"""Create all model tables

Revision ID: a117500caf8c
Revises: 597caa74eb23
Create Date: 2025-07-11 20:04:28.124055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a117500caf8c'
down_revision = '597caa74eb23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bytes_balances',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('total_received', sa.BigInteger(), nullable=False),
    sa.Column('total_sent', sa.BigInteger(), nullable=False),
    sa.Column('streak_count', sa.BigInteger(), nullable=False),
    sa.Column('last_daily', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_bytes_balances'))
    )
    op.create_table('bytes_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('daily_amount', sa.Integer(), nullable=False),
    sa.Column('daily_cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('transfer_tax_percentage', sa.Integer(), nullable=False),
    sa.Column('max_transfer_amount', sa.BigInteger(), nullable=True),
    sa.Column('streak_bonus_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_bonus_multiplier', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_bytes_configs'))
    )
    op.create_table('bytes_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('giver_id', sa.String(), nullable=False),
    sa.Column('giver_username', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=False),
    sa.Column('receiver_username', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bytes_transactions'))
    )
    with op.batch_alter_table('bytes_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_bytes_transactions_giver_id', ['giver_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_guild_giver', ['guild_id', 'giver_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_guild_receiver', ['guild_id', 'receiver_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_receiver_id', ['receiver_id'], unique=False)

    op.create_table('squads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('switch_cost', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads'))
    )
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_index('ix_squads_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_squads_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_squads_role_id', ['role_id'], unique=False)

    op.create_table('squad_memberships',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squad_memberships_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('squad_id', 'user_id', name=op.f('pk_squad_memberships'))
    )
    with op.batch_alter_table('squad_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_squad_memberships_squad_id', ['squad_id'], unique=False)
        batch_op.create_index('ix_squad_memberships_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squad_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_squad_memberships_user_id')
        batch_op.drop_index('ix_squad_memberships_squad_id')

    op.drop_table('squad_memberships')
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_index('ix_squads_role_id')
        batch_op.drop_index('ix_squads_guild_id')
        batch_op.drop_index('ix_squads_guild_active')

    op.drop_table('squads')
    with op.batch_alter_table('bytes_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_bytes_transactions_receiver_id')
        batch_op.drop_index('ix_bytes_transactions_guild_receiver')
        batch_op.drop_index('ix_bytes_transactions_guild_id')
        batch_op.drop_index('ix_bytes_transactions_guild_giver')
        batch_op.drop_index('ix_bytes_transactions_giver_id')

    op.drop_table('bytes_transactions')
    op.drop_table('bytes_configs')
    op.drop_table('bytes_balances')
    # ### end Alembic commands ###