"""Add description and revoked_at fields to APIKey model

Revision ID: ba7d71351c54
Revises: 8e8a6886849d
Create Date: 2025-07-27 21:20:44.589626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7d71351c54'
down_revision = '8e8a6886849d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_api_keys_key_hash'), ['key_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_api_keys_key_hash'), type_='unique')
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('description')

    # ### end Alembic commands ###