"""Add scheduled message fields to campaigns

Revision ID: c6ef6700c4b5
Revises: 0104bdbc8aba
Create Date: 2025-08-14 15:57:30.167938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ef6700c4b5'
down_revision = '0104bdbc8aba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_message_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('scheduled_message_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_message_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_scheduled_message_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('scheduled_message_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaigns_is_scheduled_message_sent'), ['is_scheduled_message_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_scheduled_message_time'), ['scheduled_message_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_scheduled_message_time'))
        batch_op.drop_index(batch_op.f('ix_campaigns_is_scheduled_message_sent'))
        batch_op.drop_column('scheduled_message_sent_at')
        batch_op.drop_column('is_scheduled_message_sent')
        batch_op.drop_column('scheduled_message_time')
        batch_op.drop_column('scheduled_message_description')
        batch_op.drop_column('scheduled_message_title')

    # ### end Alembic commands ###