"""Add announcement_channel_message to scheduled_messages

Revision ID: ee0ad190fc72
Revises: 1932a2acd517
Create Date: 2025-08-23 14:24:16.727094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0ad190fc72'
down_revision = '1932a2acd517'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_channel_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_column('announcement_channel_message')

    # ### end Alembic commands ###