"""Add multi-tier rate limiting to API keys

Revision ID: ee57f629d8da
Revises: d196b6fec8bf
Create Date: 2025-07-28 16:39:35.354531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee57f629d8da'
down_revision = 'd196b6fec8bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns as nullable first
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit_per_second', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rate_limit_per_15_minutes', sa.Integer(), nullable=True))
    
    # Populate default values for existing records
    op.execute("""
        UPDATE api_keys 
        SET 
            rate_limit_per_second = 10,
            rate_limit_per_minute = 180,
            rate_limit_per_15_minutes = 2500
        WHERE 
            rate_limit_per_second IS NULL 
            OR rate_limit_per_minute IS NULL 
            OR rate_limit_per_15_minutes IS NULL
    """)
    
    # Make columns non-nullable after populating defaults
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('rate_limit_per_second', nullable=False)
        batch_op.alter_column('rate_limit_per_minute', nullable=False)
        batch_op.alter_column('rate_limit_per_15_minutes', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('rate_limit_per_15_minutes')
        batch_op.drop_column('rate_limit_per_minute')
        batch_op.drop_column('rate_limit_per_second')

    # ### end Alembic commands ###