"""initial legacy schema

Revision ID: 0c69c7839de7
Revises: 
Create Date: 2026-05-04 15:33:37.755447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c69c7839de7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advent_of_code_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_advent_of_code_configs'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_15_minutes', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name='uq_api_keys_hash'),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index('ix_api_keys_active', 'api_keys', ['is_active'], unique=False, postgresql_where='is_active = true')
    op.create_index('ix_api_keys_created_by', 'api_keys', ['created_by'], unique=False)
    op.create_index('ix_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('ix_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_table('attachment_filter_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ignored_extensions', sa.JSON(), nullable=False),
    sa.Column('warn_extensions', sa.JSON(), nullable=False),
    sa.Column('warn_message', sa.Text(), nullable=True),
    sa.Column('delete_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_attachment_filter_configs'))
    )
    op.create_index('ix_attachment_filter_configs_guild_id', 'attachment_filter_configs', ['guild_id'], unique=False)
    op.create_table('audit_log_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('audit_channel_id', sa.String(), nullable=True),
    sa.Column('log_member_join', sa.Boolean(), nullable=False),
    sa.Column('log_member_leave', sa.Boolean(), nullable=False),
    sa.Column('log_member_ban', sa.Boolean(), nullable=False),
    sa.Column('log_member_unban', sa.Boolean(), nullable=False),
    sa.Column('log_message_edit', sa.Boolean(), nullable=False),
    sa.Column('log_message_delete', sa.Boolean(), nullable=False),
    sa.Column('log_username_change', sa.Boolean(), nullable=False),
    sa.Column('log_nickname_change', sa.Boolean(), nullable=False),
    sa.Column('log_role_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_audit_log_configs'))
    )
    op.create_index('ix_audit_log_configs_guild_id', 'audit_log_configs', ['guild_id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts')),
    sa.UniqueConstraint('slug', name='uq_blog_posts_slug')
    )
    op.create_index('ix_blog_posts_author', 'blog_posts', ['author'], unique=False)
    op.create_index('ix_blog_posts_created_at', 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_is_published'), 'blog_posts', ['is_published'], unique=False)
    op.create_index('ix_blog_posts_published', 'blog_posts', ['is_published', 'published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_table('bytes_balances',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('total_received', sa.BigInteger(), nullable=False),
    sa.Column('total_sent', sa.BigInteger(), nullable=False),
    sa.Column('streak_count', sa.BigInteger(), nullable=False),
    sa.Column('last_daily', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_bytes_balances'))
    )
    op.create_table('bytes_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Integer(), nullable=False),
    sa.Column('daily_amount', sa.Integer(), nullable=False),
    sa.Column('streak_bonuses', sa.JSON(), nullable=False),
    sa.Column('max_transfer', sa.Integer(), nullable=False),
    sa.Column('transfer_cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('role_rewards', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_bytes_configs'))
    )
    op.create_table('bytes_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('giver_id', sa.String(), nullable=False),
    sa.Column('giver_username', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=False),
    sa.Column('receiver_username', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bytes_transactions'))
    )
    op.create_index('ix_bytes_transactions_created_at', 'bytes_transactions', ['created_at'], unique=False)
    op.create_index('ix_bytes_transactions_giver_id', 'bytes_transactions', ['giver_id'], unique=False)
    op.create_index('ix_bytes_transactions_guild_giver', 'bytes_transactions', ['guild_id', 'giver_id'], unique=False)
    op.create_index('ix_bytes_transactions_guild_id', 'bytes_transactions', ['guild_id'], unique=False)
    op.create_index('ix_bytes_transactions_guild_receiver', 'bytes_transactions', ['guild_id', 'receiver_id'], unique=False)
    op.create_index('ix_bytes_transactions_receiver_id', 'bytes_transactions', ['receiver_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_cadence_hours', sa.Integer(), nullable=False),
    sa.Column('announcement_channels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('release_cadence_hours >= 1 AND release_cadence_hours <= 168', name=op.f('ck_campaigns_ck_campaigns_cadence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('guild_id', 'title', name='uq_campaigns_guild_title')
    )
    op.create_index('ix_campaigns_created_by', 'campaigns', ['created_by'], unique=False)
    op.create_index('ix_campaigns_guild_active', 'campaigns', ['guild_id', 'is_active'], unique=False)
    op.create_index('ix_campaigns_guild_id', 'campaigns', ['guild_id'], unique=False)
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_index('ix_campaigns_start_time', 'campaigns', ['start_time'], unique=False)
    op.create_table('forum_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('monitored_forums', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('response_threshold', sa.Float(), nullable=False),
    sa.Column('max_responses_per_hour', sa.Integer(), nullable=False),
    sa.Column('enable_user_tagging', sa.Boolean(), nullable=False),
    sa.Column('enable_responses', sa.Boolean(), nullable=False),
    sa.Column('notification_topics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_responses_per_hour >= 0', name=op.f('ck_forum_agents_ck_forum_agents_max_responses_positive')),
    sa.CheckConstraint('response_threshold >= 0.0 AND response_threshold <= 1.0', name=op.f('ck_forum_agents_ck_forum_agents_threshold_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_agents')),
    sa.UniqueConstraint('guild_id', 'name', name='uq_forum_agents_guild_name')
    )
    op.create_index('ix_forum_agents_created_by', 'forum_agents', ['created_by'], unique=False)
    op.create_index(op.f('ix_forum_agents_enable_responses'), 'forum_agents', ['enable_responses'], unique=False)
    op.create_index(op.f('ix_forum_agents_enable_user_tagging'), 'forum_agents', ['enable_user_tagging'], unique=False)
    op.create_index('ix_forum_agents_guild_active', 'forum_agents', ['guild_id', 'is_active'], unique=False)
    op.create_index('ix_forum_agents_guild_id', 'forum_agents', ['guild_id'], unique=False)
    op.create_index(op.f('ix_forum_agents_is_active'), 'forum_agents', ['is_active'], unique=False)
    op.create_table('forum_notification_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('topic_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_notification_topics')),
    sa.UniqueConstraint('guild_id', 'forum_channel_id', 'topic_name', name='uq_forum_notification_topics_guild_forum_topic')
    )
    op.create_index('ix_forum_notification_topics_forum_channel_id', 'forum_notification_topics', ['forum_channel_id'], unique=False)
    op.create_index('ix_forum_notification_topics_guild_forum', 'forum_notification_topics', ['guild_id', 'forum_channel_id'], unique=False)
    op.create_index('ix_forum_notification_topics_guild_id', 'forum_notification_topics', ['guild_id'], unique=False)
    op.create_table('forum_user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=False),
    sa.Column('subscribed_topics', sa.JSON(), nullable=False),
    sa.Column('notification_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('notification_hours = -1 OR (notification_hours >= 1 AND notification_hours <= 8760)', name=op.f('ck_forum_user_subscriptions_ck_forum_user_subscriptions_notification_hours_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_user_subscriptions')),
    sa.UniqueConstraint('guild_id', 'user_id', 'forum_channel_id', name='uq_forum_user_subscriptions_guild_user_forum')
    )
    op.create_index('ix_forum_user_subscriptions_forum_channel_id', 'forum_user_subscriptions', ['forum_channel_id'], unique=False)
    op.create_index('ix_forum_user_subscriptions_guild_forum', 'forum_user_subscriptions', ['guild_id', 'forum_channel_id'], unique=False)
    op.create_index('ix_forum_user_subscriptions_guild_id', 'forum_user_subscriptions', ['guild_id'], unique=False)
    op.create_index('ix_forum_user_subscriptions_user_id', 'forum_user_subscriptions', ['user_id'], unique=False)
    op.create_table('help_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('context_messages', sa.JSON(), nullable=True),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('retention_policy', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('command_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_conversations'))
    )
    op.create_index(op.f('ix_help_conversations_channel_id'), 'help_conversations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_help_conversations_expires_at'), 'help_conversations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_help_conversations_guild_id'), 'help_conversations', ['guild_id'], unique=False)
    op.create_index('ix_help_conversations_guild_started', 'help_conversations', ['guild_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_help_conversations_is_resolved'), 'help_conversations', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_help_conversations_is_sensitive'), 'help_conversations', ['is_sensitive'], unique=False)
    op.create_index(op.f('ix_help_conversations_last_activity_at'), 'help_conversations', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_help_conversations_session_id'), 'help_conversations', ['session_id'], unique=False)
    op.create_index('ix_help_conversations_session_started', 'help_conversations', ['session_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_help_conversations_started_at'), 'help_conversations', ['started_at'], unique=False)
    op.create_index('ix_help_conversations_tokens_started', 'help_conversations', ['tokens_used', 'started_at'], unique=False)
    op.create_index(op.f('ix_help_conversations_user_id'), 'help_conversations', ['user_id'], unique=False)
    op.create_index('ix_help_conversations_user_started', 'help_conversations', ['user_id', 'started_at'], unique=False)
    op.create_table('repeating_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('next_send_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_minutes >= 1', name=op.f('ck_repeating_messages_ck_repeating_messages_interval_positive')),
    sa.CheckConstraint('total_sent >= 0', name=op.f('ck_repeating_messages_ck_repeating_messages_total_sent_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repeating_messages'))
    )
    op.create_index('ix_repeating_messages_channel_id', 'repeating_messages', ['channel_id'], unique=False)
    op.create_index('ix_repeating_messages_created_by', 'repeating_messages', ['created_by'], unique=False)
    op.create_index('ix_repeating_messages_due', 'repeating_messages', ['is_active', 'next_send_time'], unique=False)
    op.create_index('ix_repeating_messages_guild_active', 'repeating_messages', ['guild_id', 'is_active'], unique=False)
    op.create_index('ix_repeating_messages_guild_id', 'repeating_messages', ['guild_id'], unique=False)
    op.create_index(op.f('ix_repeating_messages_is_active'), 'repeating_messages', ['is_active'], unique=False)
    op.create_index('ix_repeating_messages_next_send_time', 'repeating_messages', ['next_send_time'], unique=False)
    op.create_index(op.f('ix_repeating_messages_start_time'), 'repeating_messages', ['start_time'], unique=False)
    op.create_table('squad_sale_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('join_discount_percent', sa.Integer(), nullable=False),
    sa.Column('switch_discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_hours >= 1', name=op.f('ck_squad_sale_events_ck_squad_sale_events_duration_positive')),
    sa.CheckConstraint('join_discount_percent >= 0 AND join_discount_percent <= 100', name=op.f('ck_squad_sale_events_ck_squad_sale_events_join_discount_range')),
    sa.CheckConstraint('switch_discount_percent >= 0 AND switch_discount_percent <= 100', name=op.f('ck_squad_sale_events_ck_squad_sale_events_switch_discount_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squad_sale_events')),
    sa.UniqueConstraint('guild_id', 'name', name='uq_squad_sale_events_guild_name')
    )
    op.create_index('ix_squad_sale_events_created_by', 'squad_sale_events', ['created_by'], unique=False)
    op.create_index('ix_squad_sale_events_guild_active', 'squad_sale_events', ['guild_id', 'is_active'], unique=False)
    op.create_index('ix_squad_sale_events_guild_id', 'squad_sale_events', ['guild_id'], unique=False)
    op.create_index(op.f('ix_squad_sale_events_is_active'), 'squad_sale_events', ['is_active'], unique=False)
    op.create_index('ix_squad_sale_events_start_time', 'squad_sale_events', ['start_time'], unique=False)
    op.create_table('squads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('switch_cost', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('welcome_message', sa.String(length=500), nullable=True),
    sa.Column('announcement_channel', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads')),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_squads_guild_role')
    )
    op.create_index('ix_squads_guild_active', 'squads', ['guild_id', 'is_active'], unique=False)
    op.create_index('ix_squads_guild_default', 'squads', ['guild_id', 'is_default'], unique=False)
    op.create_index('ix_squads_guild_id', 'squads', ['guild_id'], unique=False)
    op.create_index('ix_squads_role_id', 'squads', ['role_id'], unique=False)
    op.create_table('advent_of_code_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('thread_title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['advent_of_code_configs.guild_id'], name=op.f('fk_advent_of_code_threads_guild_id_advent_of_code_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advent_of_code_threads')),
    sa.UniqueConstraint('guild_id', 'year', 'day', name='uq_aoc_thread_guild_year_day')
    )
    op.create_index('ix_aoc_threads_guild_id', 'advent_of_code_threads', ['guild_id'], unique=False)
    op.create_index('ix_aoc_threads_year_day', 'advent_of_code_threads', ['year', 'day'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('python_script', sa.Text(), nullable=True),
    sa.Column('input_generator_script', sa.Text(), nullable=True),
    sa.Column('solution_validator_script', sa.Text(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_announced', sa.Boolean(), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_position >= 1', name=op.f('ck_challenges_ck_challenges_position_positive')),
    sa.CheckConstraint('points_value >= 0', name=op.f('ck_challenges_ck_challenges_points_non_negative')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_challenges_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges')),
    sa.UniqueConstraint('campaign_id', 'order_position', name='uq_challenges_campaign_position')
    )
    op.create_index('ix_challenges_announced_at', 'challenges', ['announced_at'], unique=False)
    op.create_index('ix_challenges_campaign_id', 'challenges', ['campaign_id'], unique=False)
    op.create_index('ix_challenges_campaign_position', 'challenges', ['campaign_id', 'order_position'], unique=False)
    op.create_index('ix_challenges_is_announced', 'challenges', ['is_announced'], unique=False)
    op.create_index('ix_challenges_is_released', 'challenges', ['is_released'], unique=False)
    op.create_index(op.f('ix_challenges_order_position'), 'challenges', ['order_position'], unique=False)
    op.create_index('ix_challenges_released_at', 'challenges', ['released_at'], unique=False)
    op.create_table('forum_agent_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('post_title', sa.String(length=300), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('author_display_name', sa.String(length=100), nullable=False),
    sa.Column('post_tags', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_confidence_range')),
    sa.CheckConstraint('response_time_ms >= 0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_time_positive')),
    sa.CheckConstraint('tokens_used >= 0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_tokens_positive')),
    sa.ForeignKeyConstraint(['agent_id'], ['forum_agents.id'], name=op.f('fk_forum_agent_responses_agent_id_forum_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_agent_responses'))
    )
    op.create_index('ix_forum_agent_responses_agent_created', 'forum_agent_responses', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_forum_agent_responses_agent_id'), 'forum_agent_responses', ['agent_id'], unique=False)
    op.create_index('ix_forum_agent_responses_channel_created', 'forum_agent_responses', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_forum_agent_responses_channel_id'), 'forum_agent_responses', ['channel_id'], unique=False)
    op.create_index(op.f('ix_forum_agent_responses_created_at'), 'forum_agent_responses', ['created_at'], unique=False)
    op.create_index('ix_forum_agent_responses_guild_created', 'forum_agent_responses', ['guild_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_forum_agent_responses_guild_id'), 'forum_agent_responses', ['guild_id'], unique=False)
    op.create_index(op.f('ix_forum_agent_responses_responded'), 'forum_agent_responses', ['responded'], unique=False)
    op.create_index('ix_forum_agent_responses_responded_at', 'forum_agent_responses', ['responded_at'], unique=False)
    op.create_index(op.f('ix_forum_agent_responses_thread_id'), 'forum_agent_responses', ['thread_id'], unique=False)
    op.create_index('ix_forum_agent_responses_tokens_created', 'forum_agent_responses', ['tokens_used', 'created_at'], unique=False)
    op.create_table('scheduled_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('announcement_channel_message', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_time IS NOT NULL', name=op.f('ck_scheduled_messages_ck_scheduled_messages_time_required')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_scheduled_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_messages'))
    )
    op.create_index('ix_scheduled_messages_campaign_id', 'scheduled_messages', ['campaign_id'], unique=False)
    op.create_index('ix_scheduled_messages_campaign_time', 'scheduled_messages', ['campaign_id', 'scheduled_time'], unique=False)
    op.create_index('ix_scheduled_messages_is_sent', 'scheduled_messages', ['is_sent'], unique=False)
    op.create_index('ix_scheduled_messages_scheduled_time', 'scheduled_messages', ['scheduled_time'], unique=False)
    op.create_index('ix_scheduled_messages_sent_at', 'scheduled_messages', ['sent_at'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_security_logs_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_logs'))
    )
    op.create_index(op.f('ix_security_logs_action'), 'security_logs', ['action'], unique=False)
    op.create_index('ix_security_logs_action_timestamp', 'security_logs', ['action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_api_key_id'), 'security_logs', ['api_key_id'], unique=False)
    op.create_index('ix_security_logs_api_key_timestamp', 'security_logs', ['api_key_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_ip_address'), 'security_logs', ['ip_address'], unique=False)
    op.create_index('ix_security_logs_ip_timestamp', 'security_logs', ['ip_address', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_request_id'), 'security_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_security_logs_success'), 'security_logs', ['success'], unique=False)
    op.create_index('ix_security_logs_success_timestamp', 'security_logs', ['success', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_timestamp'), 'security_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_logs_user_identifier'), 'security_logs', ['user_identifier'], unique=False)
    op.create_index('ix_security_logs_user_timestamp', 'security_logs', ['user_identifier', 'timestamp'], unique=False)
    op.create_table('squad_memberships',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squad_memberships_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('squad_id', 'user_id', name=op.f('pk_squad_memberships'))
    )
    op.create_index('ix_squad_memberships_guild_id', 'squad_memberships', ['guild_id'], unique=False)
    op.create_index('ix_squad_memberships_guild_user', 'squad_memberships', ['guild_id', 'user_id'], unique=False)
    op.create_index('ix_squad_memberships_squad_id', 'squad_memberships', ['squad_id'], unique=False)
    op.create_index('ix_squad_memberships_user_id', 'squad_memberships', ['user_id'], unique=False)
    op.create_table('challenge_inputs',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_inputs_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_challenge_inputs_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'squad_id', name=op.f('pk_challenge_inputs'))
    )
    op.create_index('ix_challenge_inputs_challenge_id', 'challenge_inputs', ['challenge_id'], unique=False)
    op.create_index('ix_challenge_inputs_created_at', 'challenge_inputs', ['created_at'], unique=False)
    op.create_index('ix_challenge_inputs_squad_id', 'challenge_inputs', ['squad_id'], unique=False)
    op.create_table('challenge_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('submitted_solution', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_success', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_submissions_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_challenge_submissions_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_submissions'))
    )
    op.create_index(op.f('ix_challenge_submissions_challenge_id'), 'challenge_submissions', ['challenge_id'], unique=False)
    op.create_index('ix_challenge_submissions_challenge_squad', 'challenge_submissions', ['challenge_id', 'squad_id'], unique=False)
    op.create_index('ix_challenge_submissions_first_success', 'challenge_submissions', ['is_first_success', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_challenge_submissions_squad_id'), 'challenge_submissions', ['squad_id'], unique=False)
    op.create_index(op.f('ix_challenge_submissions_user_id'), 'challenge_submissions', ['user_id'], unique=False)
    op.create_index('ix_challenge_submissions_user_submitted', 'challenge_submissions', ['user_id', 'submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challenge_submissions_user_submitted', table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_submissions_user_id'), table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_submissions_squad_id'), table_name='challenge_submissions')
    op.drop_index('ix_challenge_submissions_first_success', table_name='challenge_submissions')
    op.drop_index('ix_challenge_submissions_challenge_squad', table_name='challenge_submissions')
    op.drop_index(op.f('ix_challenge_submissions_challenge_id'), table_name='challenge_submissions')
    op.drop_table('challenge_submissions')
    op.drop_index('ix_challenge_inputs_squad_id', table_name='challenge_inputs')
    op.drop_index('ix_challenge_inputs_created_at', table_name='challenge_inputs')
    op.drop_index('ix_challenge_inputs_challenge_id', table_name='challenge_inputs')
    op.drop_table('challenge_inputs')
    op.drop_index('ix_squad_memberships_user_id', table_name='squad_memberships')
    op.drop_index('ix_squad_memberships_squad_id', table_name='squad_memberships')
    op.drop_index('ix_squad_memberships_guild_user', table_name='squad_memberships')
    op.drop_index('ix_squad_memberships_guild_id', table_name='squad_memberships')
    op.drop_table('squad_memberships')
    op.drop_index('ix_security_logs_user_timestamp', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_user_identifier'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_timestamp'), table_name='security_logs')
    op.drop_index('ix_security_logs_success_timestamp', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_success'), table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_request_id'), table_name='security_logs')
    op.drop_index('ix_security_logs_ip_timestamp', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_ip_address'), table_name='security_logs')
    op.drop_index('ix_security_logs_api_key_timestamp', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_api_key_id'), table_name='security_logs')
    op.drop_index('ix_security_logs_action_timestamp', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_action'), table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index('ix_scheduled_messages_sent_at', table_name='scheduled_messages')
    op.drop_index('ix_scheduled_messages_scheduled_time', table_name='scheduled_messages')
    op.drop_index('ix_scheduled_messages_is_sent', table_name='scheduled_messages')
    op.drop_index('ix_scheduled_messages_campaign_time', table_name='scheduled_messages')
    op.drop_index('ix_scheduled_messages_campaign_id', table_name='scheduled_messages')
    op.drop_table('scheduled_messages')
    op.drop_index('ix_forum_agent_responses_tokens_created', table_name='forum_agent_responses')
    op.drop_index(op.f('ix_forum_agent_responses_thread_id'), table_name='forum_agent_responses')
    op.drop_index('ix_forum_agent_responses_responded_at', table_name='forum_agent_responses')
    op.drop_index(op.f('ix_forum_agent_responses_responded'), table_name='forum_agent_responses')
    op.drop_index(op.f('ix_forum_agent_responses_guild_id'), table_name='forum_agent_responses')
    op.drop_index('ix_forum_agent_responses_guild_created', table_name='forum_agent_responses')
    op.drop_index(op.f('ix_forum_agent_responses_created_at'), table_name='forum_agent_responses')
    op.drop_index(op.f('ix_forum_agent_responses_channel_id'), table_name='forum_agent_responses')
    op.drop_index('ix_forum_agent_responses_channel_created', table_name='forum_agent_responses')
    op.drop_index(op.f('ix_forum_agent_responses_agent_id'), table_name='forum_agent_responses')
    op.drop_index('ix_forum_agent_responses_agent_created', table_name='forum_agent_responses')
    op.drop_table('forum_agent_responses')
    op.drop_index('ix_challenges_released_at', table_name='challenges')
    op.drop_index(op.f('ix_challenges_order_position'), table_name='challenges')
    op.drop_index('ix_challenges_is_released', table_name='challenges')
    op.drop_index('ix_challenges_is_announced', table_name='challenges')
    op.drop_index('ix_challenges_campaign_position', table_name='challenges')
    op.drop_index('ix_challenges_campaign_id', table_name='challenges')
    op.drop_index('ix_challenges_announced_at', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('ix_aoc_threads_year_day', table_name='advent_of_code_threads')
    op.drop_index('ix_aoc_threads_guild_id', table_name='advent_of_code_threads')
    op.drop_table('advent_of_code_threads')
    op.drop_index('ix_squads_role_id', table_name='squads')
    op.drop_index('ix_squads_guild_id', table_name='squads')
    op.drop_index('ix_squads_guild_default', table_name='squads')
    op.drop_index('ix_squads_guild_active', table_name='squads')
    op.drop_table('squads')
    op.drop_index('ix_squad_sale_events_start_time', table_name='squad_sale_events')
    op.drop_index(op.f('ix_squad_sale_events_is_active'), table_name='squad_sale_events')
    op.drop_index('ix_squad_sale_events_guild_id', table_name='squad_sale_events')
    op.drop_index('ix_squad_sale_events_guild_active', table_name='squad_sale_events')
    op.drop_index('ix_squad_sale_events_created_by', table_name='squad_sale_events')
    op.drop_table('squad_sale_events')
    op.drop_index(op.f('ix_repeating_messages_start_time'), table_name='repeating_messages')
    op.drop_index('ix_repeating_messages_next_send_time', table_name='repeating_messages')
    op.drop_index(op.f('ix_repeating_messages_is_active'), table_name='repeating_messages')
    op.drop_index('ix_repeating_messages_guild_id', table_name='repeating_messages')
    op.drop_index('ix_repeating_messages_guild_active', table_name='repeating_messages')
    op.drop_index('ix_repeating_messages_due', table_name='repeating_messages')
    op.drop_index('ix_repeating_messages_created_by', table_name='repeating_messages')
    op.drop_index('ix_repeating_messages_channel_id', table_name='repeating_messages')
    op.drop_table('repeating_messages')
    op.drop_index('ix_help_conversations_user_started', table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_user_id'), table_name='help_conversations')
    op.drop_index('ix_help_conversations_tokens_started', table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_started_at'), table_name='help_conversations')
    op.drop_index('ix_help_conversations_session_started', table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_session_id'), table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_last_activity_at'), table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_is_sensitive'), table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_is_resolved'), table_name='help_conversations')
    op.drop_index('ix_help_conversations_guild_started', table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_guild_id'), table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_expires_at'), table_name='help_conversations')
    op.drop_index(op.f('ix_help_conversations_channel_id'), table_name='help_conversations')
    op.drop_table('help_conversations')
    op.drop_index('ix_forum_user_subscriptions_user_id', table_name='forum_user_subscriptions')
    op.drop_index('ix_forum_user_subscriptions_guild_id', table_name='forum_user_subscriptions')
    op.drop_index('ix_forum_user_subscriptions_guild_forum', table_name='forum_user_subscriptions')
    op.drop_index('ix_forum_user_subscriptions_forum_channel_id', table_name='forum_user_subscriptions')
    op.drop_table('forum_user_subscriptions')
    op.drop_index('ix_forum_notification_topics_guild_id', table_name='forum_notification_topics')
    op.drop_index('ix_forum_notification_topics_guild_forum', table_name='forum_notification_topics')
    op.drop_index('ix_forum_notification_topics_forum_channel_id', table_name='forum_notification_topics')
    op.drop_table('forum_notification_topics')
    op.drop_index(op.f('ix_forum_agents_is_active'), table_name='forum_agents')
    op.drop_index('ix_forum_agents_guild_id', table_name='forum_agents')
    op.drop_index('ix_forum_agents_guild_active', table_name='forum_agents')
    op.drop_index(op.f('ix_forum_agents_enable_user_tagging'), table_name='forum_agents')
    op.drop_index(op.f('ix_forum_agents_enable_responses'), table_name='forum_agents')
    op.drop_index('ix_forum_agents_created_by', table_name='forum_agents')
    op.drop_table('forum_agents')
    op.drop_index('ix_campaigns_start_time', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_index('ix_campaigns_guild_id', table_name='campaigns')
    op.drop_index('ix_campaigns_guild_active', table_name='campaigns')
    op.drop_index('ix_campaigns_created_by', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_bytes_transactions_receiver_id', table_name='bytes_transactions')
    op.drop_index('ix_bytes_transactions_guild_receiver', table_name='bytes_transactions')
    op.drop_index('ix_bytes_transactions_guild_id', table_name='bytes_transactions')
    op.drop_index('ix_bytes_transactions_guild_giver', table_name='bytes_transactions')
    op.drop_index('ix_bytes_transactions_giver_id', table_name='bytes_transactions')
    op.drop_index('ix_bytes_transactions_created_at', table_name='bytes_transactions')
    op.drop_table('bytes_transactions')
    op.drop_table('bytes_configs')
    op.drop_table('bytes_balances')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_published', table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_is_published'), table_name='blog_posts')
    op.drop_index('ix_blog_posts_created_at', table_name='blog_posts')
    op.drop_index('ix_blog_posts_author', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index('ix_audit_log_configs_guild_id', table_name='audit_log_configs')
    op.drop_table('audit_log_configs')
    op.drop_index('ix_attachment_filter_configs_guild_id', table_name='attachment_filter_configs')
    op.drop_table('attachment_filter_configs')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys')
    op.drop_index('ix_api_keys_hash', table_name='api_keys')
    op.drop_index('ix_api_keys_created_by', table_name='api_keys')
    op.drop_index('ix_api_keys_active', table_name='api_keys', postgresql_where='is_active = true')
    op.drop_table('api_keys')
    op.drop_table('advent_of_code_configs')
    # ### end Alembic commands ###
