"""add resources tables

Revision ID: f3c4200ddcde
Revises: 943a0157b835
Create Date: 2026-05-13 13:02:29.320982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c4200ddcde'
down_revision: Union[str, None] = '943a0157b835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm powers the GIN trigram indexes added at the bottom so we can run
    # ILIKE searches across blurbs / names / intros without sequential scans.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_directories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('track_key_prefix', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_directories')),
    sa.UniqueConstraint('slug', name=op.f('uq_resource_directories_slug')),
    sa.UniqueConstraint('track_key_prefix', name=op.f('uq_resource_directories_track_key_prefix'))
    )
    op.create_table('resource_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('byline', sa.String(length=256), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('learning_type', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('first_indexed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_sources')),
    sa.UniqueConstraint('track_key', name=op.f('uq_resource_sources_track_key'))
    )
    op.create_table('resource_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('directory_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('intro_html', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['resource_directories.id'], name=op.f('fk_resource_categories_directory_id_resource_directories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_categories')),
    sa.UniqueConstraint('directory_id', 'slug', name='uq_resource_categories_dir_slug')
    )
    op.create_table('resource_creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('directory_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('track_key', sa.String(length=200), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['resource_directories.id'], name=op.f('fk_resource_creators_directory_id_resource_directories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_creators')),
    sa.UniqueConstraint('directory_id', 'slug', name='uq_resource_creators_dir_slug'),
    sa.UniqueConstraint('track_key', name=op.f('uq_resource_creators_track_key'))
    )
    op.create_table('resource_directory_spine',
    sa.Column('directory_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['resource_directories.id'], name=op.f('fk_resource_directory_spine_directory_id_resource_directories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['resource_sources.id'], name=op.f('fk_resource_directory_spine_source_id_resource_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('directory_id', 'source_id', name=op.f('pk_resource_directory_spine'))
    )
    op.create_table('resource_faqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('directory_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source_label', sa.String(length=256), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_track_key', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['resource_directories.id'], name=op.f('fk_resource_faqs_directory_id_resource_directories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_faqs')),
    sa.UniqueConstraint('source_track_key', name=op.f('uq_resource_faqs_source_track_key'))
    )
    op.create_table('resource_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('home_track_key', sa.String(length=200), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], name=op.f('fk_resource_tools_category_id_resource_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_tools')),
    sa.UniqueConstraint('category_id', 'slug', name='uq_resource_tools_cat_slug'),
    sa.UniqueConstraint('home_track_key', name=op.f('uq_resource_tools_home_track_key'))
    )
    op.create_table('resource_tool_sources',
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['resource_sources.id'], name=op.f('fk_resource_tool_sources_source_id_resource_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['resource_tools.id'], name=op.f('fk_resource_tool_sources_tool_id_resource_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'source_id', name=op.f('pk_resource_tool_sources'))
    )
    # ### end Alembic commands ###

    # Trigram indexes for cross-directory search ("find every resource that
    # mentions Postgres / observability / etc."). One per searchable column.
    op.execute(
        "CREATE INDEX ix_resource_sources_title_trgm "
        "ON resource_sources USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_sources_blurb_trgm "
        "ON resource_sources USING gin (blurb gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_tools_name_trgm "
        "ON resource_tools USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_tools_blurb_trgm "
        "ON resource_tools USING gin (blurb gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_categories_intro_trgm "
        "ON resource_categories USING gin (intro_html gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_categories_name_trgm "
        "ON resource_categories USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_creators_blurb_trgm "
        "ON resource_creators USING gin (blurb gin_trgm_ops)"
    )

    # Seed the new tables from the legacy Python data modules so the deploy
    # that lands this migration also lands populated /resources pages.
    # The seed module is idempotent, which is what we want here: if a later
    # migration changes a column we re-run safely.
    from smarter_dev.web._resources_seed import seed_all
    seed_all(op.get_bind())


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_resource_creators_blurb_trgm")
    op.execute("DROP INDEX IF EXISTS ix_resource_categories_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_resource_categories_intro_trgm")
    op.execute("DROP INDEX IF EXISTS ix_resource_tools_blurb_trgm")
    op.execute("DROP INDEX IF EXISTS ix_resource_tools_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_resource_sources_blurb_trgm")
    op.execute("DROP INDEX IF EXISTS ix_resource_sources_title_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_tool_sources')
    op.drop_table('resource_tools')
    op.drop_table('resource_faqs')
    op.drop_table('resource_directory_spine')
    op.drop_table('resource_creators')
    op.drop_table('resource_categories')
    op.drop_table('resource_sources')
    op.drop_table('resource_directories')
    # ### end Alembic commands ###
