"""initial main schema

Revision ID: 6a448f2c9bb7
Revises: 
Create Date: 2026-05-04 15:33:27.937977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a448f2c9bb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('discord_id', sa.String(length=20), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confirmation_token', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR discord_id IS NOT NULL', name=op.f('ck_campaign_signups_at_least_one_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_signups')),
    sa.UniqueConstraint('campaign_slug', 'discord_id', name='uq_campaign_signups_slug_discord_id'),
    sa.UniqueConstraint('campaign_slug', 'email', name='uq_campaign_signups_slug_email')
    )
    op.create_index(op.f('ix_campaign_signups_campaign_slug'), 'campaign_signups', ['campaign_slug'], unique=False)
    op.create_index(op.f('ix_campaign_signups_confirmation_token'), 'campaign_signups', ['confirmation_token'], unique=True)
    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.String(), nullable=False),
    sa.Column('target_username', sa.String(), nullable=False),
    sa.Column('moderator_user_id', sa.String(), nullable=True),
    sa.Column('moderator_username', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='ai', nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('trigger_message_id', sa.String(), nullable=True),
    sa.Column('ai_context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_actions'))
    )
    op.create_index('ix_mod_actions_guild_type', 'moderation_actions', ['guild_id', 'action_type'], unique=False)
    op.create_index('ix_mod_actions_guild_user', 'moderation_actions', ['guild_id', 'target_user_id'], unique=False)
    op.create_table('moderation_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitored_role_ids', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('enabled_tools', sa.JSON(), server_default='["timeout", "purge", "delete"]', nullable=False),
    sa.Column('response_channel_id', sa.String(), nullable=True),
    sa.Column('context_message_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_moderation_configs'))
    )
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('python_script', sa.Text(), nullable=True),
    sa.Column('input_generator_script', sa.Text(), nullable=True),
    sa.Column('solution_validator_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    op.create_index('ix_quests_guild_id', 'quests', ['guild_id'], unique=False)
    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('guild_id', sa.String(length=20), nullable=True),
    sa.Column('channel_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('tool_log', sa.JSON(), nullable=True),
    sa.Column('followups', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('pipeline_mode', sa.String(length=20), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sessions'))
    )
    op.create_index(op.f('ix_research_sessions_slug'), 'research_sessions', ['slug'], unique=True)
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    op.create_table('scan_service_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_service_usage'))
    )
    op.create_index(op.f('ix_scan_service_usage_task_type'), 'scan_service_usage', ['task_type'], unique=False)
    op.create_table('scan_user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('recent_queries', sa.JSON(), nullable=True),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('suggested_queries', sa.JSON(), nullable=True),
    sa.Column('opt_out_narrative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opt_out_technologies', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_user_profiles'))
    )
    op.create_index(op.f('ix_scan_user_profiles_user_id'), 'scan_user_profiles', ['user_id'], unique=True)
    op.create_table('daily_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('is_announced', sa.Boolean(), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_daily_quests_quest_id_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_quests')),
    sa.UniqueConstraint('guild_id', 'quest_id', 'active_date', name='uq_daily_quests_per_day')
    )
    op.create_index(op.f('ix_daily_quests_active_date'), 'daily_quests', ['active_date'], unique=False)
    op.create_index(op.f('ix_daily_quests_announced_at'), 'daily_quests', ['announced_at'], unique=False)
    op.create_index('ix_daily_quests_guild_date', 'daily_quests', ['guild_id', 'active_date'], unique=False)
    op.create_index(op.f('ix_daily_quests_guild_id'), 'daily_quests', ['guild_id'], unique=False)
    op.create_index(op.f('ix_daily_quests_is_active'), 'daily_quests', ['is_active'], unique=False)
    op.create_index(op.f('ix_daily_quests_is_announced'), 'daily_quests', ['is_announced'], unique=False)
    op.create_index(op.f('ix_daily_quests_quest_id'), 'daily_quests', ['quest_id'], unique=False)
    op.create_table('quest_inputs',
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_inputs_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_quest_id', name=op.f('pk_quest_inputs'))
    )
    op.create_table('quest_progress',
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_progress_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_quest_id', 'user_id', name=op.f('pk_quest_progress'))
    )
    op.create_index(op.f('ix_quest_progress_guild_id'), 'quest_progress', ['guild_id'], unique=False)
    op.create_index('ix_quest_progress_guild_user', 'quest_progress', ['guild_id', 'user_id'], unique=False)
    op.create_table('quest_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('submitted_solution', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_success', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_submissions_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest_submissions'))
    )
    op.create_index(op.f('ix_quest_submissions_daily_quest_id'), 'quest_submissions', ['daily_quest_id'], unique=False)
    op.create_index('ix_quest_submissions_daily_squad_first', 'quest_submissions', ['daily_quest_id', 'squad_id', 'is_first_success'], unique=False)
    op.create_index(op.f('ix_quest_submissions_guild_id'), 'quest_submissions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_quest_submissions_is_first_success'), 'quest_submissions', ['is_first_success'], unique=False)
    op.create_index(op.f('ix_quest_submissions_squad_id'), 'quest_submissions', ['squad_id'], unique=False)
    op.create_index(op.f('ix_quest_submissions_user_id'), 'quest_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_submissions_user_id'), table_name='quest_submissions')
    op.drop_index(op.f('ix_quest_submissions_squad_id'), table_name='quest_submissions')
    op.drop_index(op.f('ix_quest_submissions_is_first_success'), table_name='quest_submissions')
    op.drop_index(op.f('ix_quest_submissions_guild_id'), table_name='quest_submissions')
    op.drop_index('ix_quest_submissions_daily_squad_first', table_name='quest_submissions')
    op.drop_index(op.f('ix_quest_submissions_daily_quest_id'), table_name='quest_submissions')
    op.drop_table('quest_submissions')
    op.drop_index('ix_quest_progress_guild_user', table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_guild_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_table('quest_inputs')
    op.drop_index(op.f('ix_daily_quests_quest_id'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_is_announced'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_is_active'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_guild_id'), table_name='daily_quests')
    op.drop_index('ix_daily_quests_guild_date', table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_announced_at'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_active_date'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_scan_user_profiles_user_id'), table_name='scan_user_profiles')
    op.drop_table('scan_user_profiles')
    op.drop_index(op.f('ix_scan_service_usage_task_type'), table_name='scan_service_usage')
    op.drop_table('scan_service_usage')
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_index(op.f('ix_research_sessions_slug'), table_name='research_sessions')
    op.drop_table('research_sessions')
    op.drop_index('ix_quests_guild_id', table_name='quests')
    op.drop_table('quests')
    op.drop_table('moderation_configs')
    op.drop_index('ix_mod_actions_guild_user', table_name='moderation_actions')
    op.drop_index('ix_mod_actions_guild_type', table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_campaign_signups_confirmation_token'), table_name='campaign_signups')
    op.drop_index(op.f('ix_campaign_signups_campaign_slug'), table_name='campaign_signups')
    op.drop_table('campaign_signups')
    # ### end Alembic commands ###
