---
apiVersion: v1
kind: Service
metadata:
    name: smarter-dev-website
    namespace: smarter-dev
    labels:
        app: smarter-dev-website
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 8000
        name: http
    selector:
        app: smarter-dev-website
        tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: smarter-dev-website
    namespace: smarter-dev
    labels:
        app: smarter-dev-website
    annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
    tls:
      - hosts:
        - smarter.dev
        secretName: smarter-dev-website-cert
    rules:
      - host: smarter.dev
        http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: smarter-dev-website
                    port:
                      number: 8000
