"""Add challenge announcement tracking fields

Revision ID: 0104bdbc8aba
Revises: dbff96c07f61
Create Date: 2025-08-14 15:14:45.186098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0104bdbc8aba'
down_revision = 'dbff96c07f61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        # Add nullable column first, then set default values and make it non-null
        batch_op.add_column(sa.Column('is_announced', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE challenges SET is_announced = false WHERE is_announced IS NULL")
    
    # Now make the column non-null
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.alter_column('is_announced', nullable=False)
        batch_op.create_index(batch_op.f('ix_challenges_announced_at'), ['announced_at'], unique=False)
        batch_op.create_index('ix_challenges_is_announced', ['is_announced'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_challenges_is_announced')
        batch_op.drop_index(batch_op.f('ix_challenges_announced_at'))
        batch_op.drop_column('announced_at')
        batch_op.drop_column('is_announced')

    # ### end Alembic commands ###