"""Update models with Session 2 specification compliance changes

Revision ID: 1823b62b9ffc
Revises: a117500caf8c
Create Date: 2025-07-12 21:10:59.528013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1823b62b9ffc'
down_revision = 'a117500caf8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bytes_balances', schema=None) as batch_op:
        batch_op.alter_column('last_daily',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('bytes_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_balance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('streak_bonuses', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('max_transfer', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transfer_cooldown_hours', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role_rewards', sa.JSON(), nullable=False))
        batch_op.drop_column('streak_bonus_multiplier')
        batch_op.drop_column('transfer_tax_percentage')
        batch_op.drop_column('max_transfer_amount')
        batch_op.drop_column('daily_cooldown_hours')
        batch_op.drop_column('streak_bonus_enabled')

    with op.batch_alter_table('bytes_transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_index('ix_bytes_transactions_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('squad_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guild_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('squad_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index('ix_squad_memberships_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_squad_memberships_guild_user', ['guild_id', 'user_id'], unique=False)

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_squads_guild_role', ['guild_id', 'role_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_constraint('uq_squads_guild_role', type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('squad_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_squad_memberships_guild_user')
        batch_op.drop_index('ix_squad_memberships_guild_id')
        batch_op.alter_column('squad_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('joined_at')
        batch_op.drop_column('guild_id')

    with op.batch_alter_table('bytes_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_bytes_transactions_created_at')
        batch_op.alter_column('reason',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('bytes_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_bonus_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('daily_cooldown_hours', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('max_transfer_amount', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('transfer_tax_percentage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('streak_bonus_multiplier', sa.FLOAT(), nullable=False))
        batch_op.drop_column('role_rewards')
        batch_op.drop_column('transfer_cooldown_hours')
        batch_op.drop_column('max_transfer')
        batch_op.drop_column('streak_bonuses')
        batch_op.drop_column('starting_balance')

    with op.batch_alter_table('bytes_balances', schema=None) as batch_op:
        batch_op.alter_column('last_daily',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###