"""Add announcement_channel to squads table

Revision ID: 1932a2acd517
Revises: 33ca798f1a90
Create Date: 2025-08-23 08:52:03.663735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1932a2acd517'
down_revision = '33ca798f1a90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_api_keys_key_hash'), ['key_hash'])

    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_channel', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_column('announcement_channel')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_api_keys_key_hash'), type_='unique')

    # ### end Alembic commands ###