"""add_repeating_messages_table

Revision ID: 1f214f10f9ba
Revises: ee0ad190fc72
Create Date: 2025-08-24 18:44:56.520290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f214f10f9ba'
down_revision = 'ee0ad190fc72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repeating_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('next_send_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_minutes >= 1', name=op.f('ck_repeating_messages_ck_repeating_messages_interval_positive')),
    sa.CheckConstraint('total_sent >= 0', name=op.f('ck_repeating_messages_ck_repeating_messages_total_sent_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repeating_messages'))
    )
    with op.batch_alter_table('repeating_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repeating_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index('ix_repeating_messages_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_repeating_messages_due', ['is_active', 'next_send_time'], unique=False)
        batch_op.create_index('ix_repeating_messages_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_repeating_messages_guild_id', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repeating_messages_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_repeating_messages_next_send_time'), ['next_send_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_repeating_messages_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repeating_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repeating_messages_start_time'))
        batch_op.drop_index(batch_op.f('ix_repeating_messages_next_send_time'))
        batch_op.drop_index(batch_op.f('ix_repeating_messages_is_active'))
        batch_op.drop_index('ix_repeating_messages_guild_id')
        batch_op.drop_index('ix_repeating_messages_guild_active')
        batch_op.drop_index('ix_repeating_messages_due')
        batch_op.drop_index('ix_repeating_messages_created_by')
        batch_op.drop_index(batch_op.f('ix_repeating_messages_channel_id'))

    op.drop_table('repeating_messages')
    # ### end Alembic commands ###