"""Squashed initial schema

Revision ID: 2ad536d174d5
Revises: 
Create Date: 2026-05-04 14:04:37.546342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad536d174d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advent_of_code_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_advent_of_code_configs'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_second', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_15_minutes', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name='uq_api_keys_hash'),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('ix_api_keys_active', ['is_active'], unique=False, postgresql_where='is_active = true')
        batch_op.create_index('ix_api_keys_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_api_keys_hash', ['key_hash'], unique=False)
        batch_op.create_index('ix_api_keys_prefix', ['key_prefix'], unique=False)

    op.create_table('attachment_filter_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ignored_extensions', sa.JSON(), nullable=False),
    sa.Column('warn_extensions', sa.JSON(), nullable=False),
    sa.Column('warn_message', sa.Text(), nullable=True),
    sa.Column('delete_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_attachment_filter_configs'))
    )
    with op.batch_alter_table('attachment_filter_configs', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_filter_configs_guild_id', ['guild_id'], unique=False)

    op.create_table('audit_log_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('audit_channel_id', sa.String(), nullable=True),
    sa.Column('log_member_join', sa.Boolean(), nullable=False),
    sa.Column('log_member_leave', sa.Boolean(), nullable=False),
    sa.Column('log_member_ban', sa.Boolean(), nullable=False),
    sa.Column('log_member_unban', sa.Boolean(), nullable=False),
    sa.Column('log_message_edit', sa.Boolean(), nullable=False),
    sa.Column('log_message_delete', sa.Boolean(), nullable=False),
    sa.Column('log_username_change', sa.Boolean(), nullable=False),
    sa.Column('log_nickname_change', sa.Boolean(), nullable=False),
    sa.Column('log_role_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_audit_log_configs'))
    )
    with op.batch_alter_table('audit_log_configs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_configs_guild_id', ['guild_id'], unique=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts')),
    sa.UniqueConstraint('slug', name='uq_blog_posts_slug')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index('ix_blog_posts_author', ['author'], unique=False)
        batch_op.create_index('ix_blog_posts_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_is_published'), ['is_published'], unique=False)
        batch_op.create_index('ix_blog_posts_published', ['is_published', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)

    op.create_table('bytes_balances',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('total_received', sa.BigInteger(), nullable=False),
    sa.Column('total_sent', sa.BigInteger(), nullable=False),
    sa.Column('streak_count', sa.BigInteger(), nullable=False),
    sa.Column('last_daily', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name=op.f('pk_bytes_balances'))
    )
    op.create_table('bytes_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Integer(), nullable=False),
    sa.Column('daily_amount', sa.Integer(), nullable=False),
    sa.Column('streak_bonuses', sa.JSON(), nullable=False),
    sa.Column('max_transfer', sa.Integer(), nullable=False),
    sa.Column('transfer_cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('role_rewards', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_bytes_configs'))
    )
    op.create_table('bytes_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('giver_id', sa.String(), nullable=False),
    sa.Column('giver_username', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=False),
    sa.Column('receiver_username', sa.String(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bytes_transactions'))
    )
    with op.batch_alter_table('bytes_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_bytes_transactions_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_bytes_transactions_giver_id', ['giver_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_guild_giver', ['guild_id', 'giver_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_guild_receiver', ['guild_id', 'receiver_id'], unique=False)
        batch_op.create_index('ix_bytes_transactions_receiver_id', ['receiver_id'], unique=False)

    op.create_table('campaign_signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('discord_id', sa.String(length=20), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confirmation_token', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR discord_id IS NOT NULL', name=op.f('ck_campaign_signups_at_least_one_contact')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_signups')),
    sa.UniqueConstraint('campaign_slug', 'discord_id', name='uq_campaign_signups_slug_discord_id'),
    sa.UniqueConstraint('campaign_slug', 'email', name='uq_campaign_signups_slug_email')
    )
    with op.batch_alter_table('campaign_signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_signups_campaign_slug'), ['campaign_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_signups_confirmation_token'), ['confirmation_token'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('release_cadence_hours', sa.Integer(), nullable=False),
    sa.Column('announcement_channels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('release_cadence_hours >= 1 AND release_cadence_hours <= 168', name=op.f('ck_campaigns_ck_campaigns_cadence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('guild_id', 'title', name='uq_campaigns_guild_title')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_campaigns_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_campaigns_guild_id', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_campaigns_start_time', ['start_time'], unique=False)

    op.create_table('forum_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('monitored_forums', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('response_threshold', sa.Float(), nullable=False),
    sa.Column('max_responses_per_hour', sa.Integer(), nullable=False),
    sa.Column('enable_user_tagging', sa.Boolean(), nullable=False),
    sa.Column('enable_responses', sa.Boolean(), nullable=False),
    sa.Column('notification_topics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_responses_per_hour >= 0', name=op.f('ck_forum_agents_ck_forum_agents_max_responses_positive')),
    sa.CheckConstraint('response_threshold >= 0.0 AND response_threshold <= 1.0', name=op.f('ck_forum_agents_ck_forum_agents_threshold_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_agents')),
    sa.UniqueConstraint('guild_id', 'name', name='uq_forum_agents_guild_name')
    )
    with op.batch_alter_table('forum_agents', schema=None) as batch_op:
        batch_op.create_index('ix_forum_agents_created_by', ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_enable_responses'), ['enable_responses'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_enable_user_tagging'), ['enable_user_tagging'], unique=False)
        batch_op.create_index('ix_forum_agents_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_forum_agents_guild_id', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_is_active'), ['is_active'], unique=False)

    op.create_table('forum_notification_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('topic_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_notification_topics')),
    sa.UniqueConstraint('guild_id', 'forum_channel_id', 'topic_name', name='uq_forum_notification_topics_guild_forum_topic')
    )
    with op.batch_alter_table('forum_notification_topics', schema=None) as batch_op:
        batch_op.create_index('ix_forum_notification_topics_forum_channel_id', ['forum_channel_id'], unique=False)
        batch_op.create_index('ix_forum_notification_topics_guild_forum', ['guild_id', 'forum_channel_id'], unique=False)
        batch_op.create_index('ix_forum_notification_topics_guild_id', ['guild_id'], unique=False)

    op.create_table('forum_user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('forum_channel_id', sa.String(), nullable=False),
    sa.Column('subscribed_topics', sa.JSON(), nullable=False),
    sa.Column('notification_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('notification_hours = -1 OR (notification_hours >= 1 AND notification_hours <= 8760)', name=op.f('ck_forum_user_subscriptions_ck_forum_user_subscriptions_notification_hours_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_user_subscriptions')),
    sa.UniqueConstraint('guild_id', 'user_id', 'forum_channel_id', name='uq_forum_user_subscriptions_guild_user_forum')
    )
    with op.batch_alter_table('forum_user_subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_forum_user_subscriptions_forum_channel_id', ['forum_channel_id'], unique=False)
        batch_op.create_index('ix_forum_user_subscriptions_guild_forum', ['guild_id', 'forum_channel_id'], unique=False)
        batch_op.create_index('ix_forum_user_subscriptions_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_forum_user_subscriptions_user_id', ['user_id'], unique=False)

    op.create_table('help_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('context_messages', sa.JSON(), nullable=True),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('retention_policy', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('command_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_conversations'))
    )
    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_conversations_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index('ix_help_conversations_guild_started', ['guild_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_is_sensitive'), ['is_sensitive'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_help_conversations_session_started', ['session_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_started_at'), ['started_at'], unique=False)
        batch_op.create_index('ix_help_conversations_tokens_started', ['tokens_used', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_help_conversations_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.String(), nullable=False),
    sa.Column('target_username', sa.String(), nullable=False),
    sa.Column('moderator_user_id', sa.String(), nullable=True),
    sa.Column('moderator_username', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='ai', nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('trigger_message_id', sa.String(), nullable=True),
    sa.Column('ai_context_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_actions'))
    )
    with op.batch_alter_table('moderation_actions', schema=None) as batch_op:
        batch_op.create_index('ix_mod_actions_guild_type', ['guild_id', 'action_type'], unique=False)
        batch_op.create_index('ix_mod_actions_guild_user', ['guild_id', 'target_user_id'], unique=False)

    op.create_table('moderation_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitored_role_ids', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('enabled_tools', sa.JSON(), server_default='["timeout", "purge", "delete"]', nullable=False),
    sa.Column('response_channel_id', sa.String(), nullable=True),
    sa.Column('context_message_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_moderation_configs'))
    )
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('python_script', sa.Text(), nullable=True),
    sa.Column('input_generator_script', sa.Text(), nullable=True),
    sa.Column('solution_validator_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quests'))
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index('ix_quests_guild_id', ['guild_id'], unique=False)

    op.create_table('repeating_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('next_send_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interval_minutes >= 1', name=op.f('ck_repeating_messages_ck_repeating_messages_interval_positive')),
    sa.CheckConstraint('total_sent >= 0', name=op.f('ck_repeating_messages_ck_repeating_messages_total_sent_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repeating_messages'))
    )
    with op.batch_alter_table('repeating_messages', schema=None) as batch_op:
        batch_op.create_index('ix_repeating_messages_channel_id', ['channel_id'], unique=False)
        batch_op.create_index('ix_repeating_messages_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_repeating_messages_due', ['is_active', 'next_send_time'], unique=False)
        batch_op.create_index('ix_repeating_messages_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_repeating_messages_guild_id', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repeating_messages_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_repeating_messages_next_send_time', ['next_send_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_repeating_messages_start_time'), ['start_time'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('guild_id', sa.String(length=20), nullable=True),
    sa.Column('channel_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('tool_log', sa.JSON(), nullable=True),
    sa.Column('followups', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('pipeline_mode', sa.String(length=20), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sessions'))
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('scan_service_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_service_usage'))
    )
    with op.batch_alter_table('scan_service_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_service_usage_task_type'), ['task_type'], unique=False)

    op.create_table('scan_user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('recent_queries', sa.JSON(), nullable=True),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('suggested_queries', sa.JSON(), nullable=True),
    sa.Column('opt_out_narrative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opt_out_technologies', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_user_profiles'))
    )
    with op.batch_alter_table('scan_user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('squad_sale_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('join_discount_percent', sa.Integer(), nullable=False),
    sa.Column('switch_discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_hours >= 1', name=op.f('ck_squad_sale_events_ck_squad_sale_events_duration_positive')),
    sa.CheckConstraint('join_discount_percent >= 0 AND join_discount_percent <= 100', name=op.f('ck_squad_sale_events_ck_squad_sale_events_join_discount_range')),
    sa.CheckConstraint('switch_discount_percent >= 0 AND switch_discount_percent <= 100', name=op.f('ck_squad_sale_events_ck_squad_sale_events_switch_discount_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squad_sale_events')),
    sa.UniqueConstraint('guild_id', 'name', name='uq_squad_sale_events_guild_name')
    )
    with op.batch_alter_table('squad_sale_events', schema=None) as batch_op:
        batch_op.create_index('ix_squad_sale_events_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_squad_sale_events_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_squad_sale_events_guild_id', ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squad_sale_events_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_squad_sale_events_start_time', ['start_time'], unique=False)

    op.create_table('squads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('switch_cost', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('welcome_message', sa.String(length=500), nullable=True),
    sa.Column('announcement_channel', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads')),
    sa.UniqueConstraint('guild_id', 'role_id', name='uq_squads_guild_role')
    )
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_index('ix_squads_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index('ix_squads_guild_default', ['guild_id', 'is_default'], unique=False)
        batch_op.create_index('ix_squads_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_squads_role_id', ['role_id'], unique=False)

    op.create_table('advent_of_code_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('thread_title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['advent_of_code_configs.guild_id'], name=op.f('fk_advent_of_code_threads_guild_id_advent_of_code_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advent_of_code_threads')),
    sa.UniqueConstraint('guild_id', 'year', 'day', name='uq_aoc_thread_guild_year_day')
    )
    with op.batch_alter_table('advent_of_code_threads', schema=None) as batch_op:
        batch_op.create_index('ix_aoc_threads_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_aoc_threads_year_day', ['year', 'day'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('python_script', sa.Text(), nullable=True),
    sa.Column('input_generator_script', sa.Text(), nullable=True),
    sa.Column('solution_validator_script', sa.Text(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_announced', sa.Boolean(), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_position >= 1', name=op.f('ck_challenges_ck_challenges_position_positive')),
    sa.CheckConstraint('points_value >= 0', name=op.f('ck_challenges_ck_challenges_points_non_negative')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_challenges_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges')),
    sa.UniqueConstraint('campaign_id', 'order_position', name='uq_challenges_campaign_position')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index('ix_challenges_announced_at', ['announced_at'], unique=False)
        batch_op.create_index('ix_challenges_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('ix_challenges_campaign_position', ['campaign_id', 'order_position'], unique=False)
        batch_op.create_index('ix_challenges_is_announced', ['is_announced'], unique=False)
        batch_op.create_index('ix_challenges_is_released', ['is_released'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenges_order_position'), ['order_position'], unique=False)
        batch_op.create_index('ix_challenges_released_at', ['released_at'], unique=False)

    op.create_table('daily_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('is_announced', sa.Boolean(), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_daily_quests_quest_id_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_quests')),
    sa.UniqueConstraint('guild_id', 'quest_id', 'active_date', name='uq_daily_quests_per_day')
    )
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_quests_active_date'), ['active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_announced_at'), ['announced_at'], unique=False)
        batch_op.create_index('ix_daily_quests_guild_date', ['guild_id', 'active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_is_announced'), ['is_announced'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quests_quest_id'), ['quest_id'], unique=False)

    op.create_table('forum_agent_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('post_title', sa.String(length=300), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('author_display_name', sa.String(length=100), nullable=False),
    sa.Column('post_tags', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_confidence_range')),
    sa.CheckConstraint('response_time_ms >= 0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_time_positive')),
    sa.CheckConstraint('tokens_used >= 0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_tokens_positive')),
    sa.ForeignKeyConstraint(['agent_id'], ['forum_agents.id'], name=op.f('fk_forum_agent_responses_agent_id_forum_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_agent_responses'))
    )
    with op.batch_alter_table('forum_agent_responses', schema=None) as batch_op:
        batch_op.create_index('ix_forum_agent_responses_agent_created', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_channel_created', ['channel_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_guild_created', ['guild_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_responded'), ['responded'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_responded_at', ['responded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_tokens_created', ['tokens_used', 'created_at'], unique=False)

    op.create_table('scheduled_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('announcement_channel_message', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_time IS NOT NULL', name=op.f('ck_scheduled_messages_ck_scheduled_messages_time_required')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_scheduled_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_messages'))
    )
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_messages_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('ix_scheduled_messages_campaign_time', ['campaign_id', 'scheduled_time'], unique=False)
        batch_op.create_index('ix_scheduled_messages_is_sent', ['is_sent'], unique=False)
        batch_op.create_index('ix_scheduled_messages_scheduled_time', ['scheduled_time'], unique=False)
        batch_op.create_index('ix_scheduled_messages_sent_at', ['sent_at'], unique=False)

    op.create_table('security_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('fk_security_logs_api_key_id_api_keys'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_logs'))
    )
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_security_logs_action_timestamp', ['action', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index('ix_security_logs_api_key_timestamp', ['api_key_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index('ix_security_logs_ip_timestamp', ['ip_address', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_success'), ['success'], unique=False)
        batch_op.create_index('ix_security_logs_success_timestamp', ['success', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_logs_user_identifier'), ['user_identifier'], unique=False)
        batch_op.create_index('ix_security_logs_user_timestamp', ['user_identifier', 'timestamp'], unique=False)

    op.create_table('squad_memberships',
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squad_memberships_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('squad_id', 'user_id', name=op.f('pk_squad_memberships'))
    )
    with op.batch_alter_table('squad_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_squad_memberships_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_squad_memberships_guild_user', ['guild_id', 'user_id'], unique=False)
        batch_op.create_index('ix_squad_memberships_squad_id', ['squad_id'], unique=False)
        batch_op.create_index('ix_squad_memberships_user_id', ['user_id'], unique=False)

    op.create_table('challenge_inputs',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_inputs_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_challenge_inputs_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'squad_id', name=op.f('pk_challenge_inputs'))
    )
    with op.batch_alter_table('challenge_inputs', schema=None) as batch_op:
        batch_op.create_index('ix_challenge_inputs_challenge_id', ['challenge_id'], unique=False)
        batch_op.create_index('ix_challenge_inputs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_challenge_inputs_squad_id', ['squad_id'], unique=False)

    op.create_table('challenge_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('submitted_solution', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_success', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_submissions_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_challenge_submissions_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_submissions'))
    )
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_submissions_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index('ix_challenge_submissions_challenge_squad', ['challenge_id', 'squad_id'], unique=False)
        batch_op.create_index('ix_challenge_submissions_first_success', ['is_first_success', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_submissions_squad_id'), ['squad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_submissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_challenge_submissions_user_submitted', ['user_id', 'submitted_at'], unique=False)

    op.create_table('quest_inputs',
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_inputs_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_quest_id', name=op.f('pk_quest_inputs'))
    )
    op.create_table('quest_progress',
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_progress_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('daily_quest_id', 'user_id', name=op.f('pk_quest_progress'))
    )
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_progress_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index('ix_quest_progress_guild_user', ['guild_id', 'user_id'], unique=False)

    op.create_table('quest_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_quest_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('submitted_solution', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_success', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_quest_id'], ['daily_quests.id'], name=op.f('fk_quest_submissions_daily_quest_id_daily_quests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quest_submissions'))
    )
    with op.batch_alter_table('quest_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_submissions_daily_quest_id'), ['daily_quest_id'], unique=False)
        batch_op.create_index('ix_quest_submissions_daily_squad_first', ['daily_quest_id', 'squad_id', 'is_first_success'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_is_first_success'), ['is_first_success'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_squad_id'), ['squad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_quest_submissions_squad_id'))
        batch_op.drop_index(batch_op.f('ix_quest_submissions_is_first_success'))
        batch_op.drop_index(batch_op.f('ix_quest_submissions_guild_id'))
        batch_op.drop_index('ix_quest_submissions_daily_squad_first')
        batch_op.drop_index(batch_op.f('ix_quest_submissions_daily_quest_id'))

    op.drop_table('quest_submissions')
    with op.batch_alter_table('quest_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_quest_progress_guild_user')
        batch_op.drop_index(batch_op.f('ix_quest_progress_guild_id'))

    op.drop_table('quest_progress')
    op.drop_table('quest_inputs')
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_challenge_submissions_user_submitted')
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_squad_id'))
        batch_op.drop_index('ix_challenge_submissions_first_success')
        batch_op.drop_index('ix_challenge_submissions_challenge_squad')
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_challenge_id'))

    op.drop_table('challenge_submissions')
    with op.batch_alter_table('challenge_inputs', schema=None) as batch_op:
        batch_op.drop_index('ix_challenge_inputs_squad_id')
        batch_op.drop_index('ix_challenge_inputs_created_at')
        batch_op.drop_index('ix_challenge_inputs_challenge_id')

    op.drop_table('challenge_inputs')
    with op.batch_alter_table('squad_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_squad_memberships_user_id')
        batch_op.drop_index('ix_squad_memberships_squad_id')
        batch_op.drop_index('ix_squad_memberships_guild_user')
        batch_op.drop_index('ix_squad_memberships_guild_id')

    op.drop_table('squad_memberships')
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_security_logs_user_timestamp')
        batch_op.drop_index(batch_op.f('ix_security_logs_user_identifier'))
        batch_op.drop_index(batch_op.f('ix_security_logs_timestamp'))
        batch_op.drop_index('ix_security_logs_success_timestamp')
        batch_op.drop_index(batch_op.f('ix_security_logs_success'))
        batch_op.drop_index(batch_op.f('ix_security_logs_request_id'))
        batch_op.drop_index('ix_security_logs_ip_timestamp')
        batch_op.drop_index(batch_op.f('ix_security_logs_ip_address'))
        batch_op.drop_index('ix_security_logs_api_key_timestamp')
        batch_op.drop_index(batch_op.f('ix_security_logs_api_key_id'))
        batch_op.drop_index('ix_security_logs_action_timestamp')
        batch_op.drop_index(batch_op.f('ix_security_logs_action'))

    op.drop_table('security_logs')
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_messages_sent_at')
        batch_op.drop_index('ix_scheduled_messages_scheduled_time')
        batch_op.drop_index('ix_scheduled_messages_is_sent')
        batch_op.drop_index('ix_scheduled_messages_campaign_time')
        batch_op.drop_index('ix_scheduled_messages_campaign_id')

    op.drop_table('scheduled_messages')
    with op.batch_alter_table('forum_agent_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_forum_agent_responses_tokens_created')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_thread_id'))
        batch_op.drop_index('ix_forum_agent_responses_responded_at')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_responded'))
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_guild_id'))
        batch_op.drop_index('ix_forum_agent_responses_guild_created')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_channel_id'))
        batch_op.drop_index('ix_forum_agent_responses_channel_created')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_agent_id'))
        batch_op.drop_index('ix_forum_agent_responses_agent_created')

    op.drop_table('forum_agent_responses')
    with op.batch_alter_table('daily_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_quests_quest_id'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_is_announced'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_is_active'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_guild_id'))
        batch_op.drop_index('ix_daily_quests_guild_date')
        batch_op.drop_index(batch_op.f('ix_daily_quests_announced_at'))
        batch_op.drop_index(batch_op.f('ix_daily_quests_active_date'))

    op.drop_table('daily_quests')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_challenges_released_at')
        batch_op.drop_index(batch_op.f('ix_challenges_order_position'))
        batch_op.drop_index('ix_challenges_is_released')
        batch_op.drop_index('ix_challenges_is_announced')
        batch_op.drop_index('ix_challenges_campaign_position')
        batch_op.drop_index('ix_challenges_campaign_id')
        batch_op.drop_index('ix_challenges_announced_at')

    op.drop_table('challenges')
    with op.batch_alter_table('advent_of_code_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_aoc_threads_year_day')
        batch_op.drop_index('ix_aoc_threads_guild_id')

    op.drop_table('advent_of_code_threads')
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_index('ix_squads_role_id')
        batch_op.drop_index('ix_squads_guild_id')
        batch_op.drop_index('ix_squads_guild_default')
        batch_op.drop_index('ix_squads_guild_active')

    op.drop_table('squads')
    with op.batch_alter_table('squad_sale_events', schema=None) as batch_op:
        batch_op.drop_index('ix_squad_sale_events_start_time')
        batch_op.drop_index(batch_op.f('ix_squad_sale_events_is_active'))
        batch_op.drop_index('ix_squad_sale_events_guild_id')
        batch_op.drop_index('ix_squad_sale_events_guild_active')
        batch_op.drop_index('ix_squad_sale_events_created_by')

    op.drop_table('squad_sale_events')
    with op.batch_alter_table('scan_user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_user_profiles_user_id'))

    op.drop_table('scan_user_profiles')
    with op.batch_alter_table('scan_service_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_service_usage_task_type'))

    op.drop_table('scan_service_usage')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_slug'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('repeating_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repeating_messages_start_time'))
        batch_op.drop_index('ix_repeating_messages_next_send_time')
        batch_op.drop_index(batch_op.f('ix_repeating_messages_is_active'))
        batch_op.drop_index('ix_repeating_messages_guild_id')
        batch_op.drop_index('ix_repeating_messages_guild_active')
        batch_op.drop_index('ix_repeating_messages_due')
        batch_op.drop_index('ix_repeating_messages_created_by')
        batch_op.drop_index('ix_repeating_messages_channel_id')

    op.drop_table('repeating_messages')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index('ix_quests_guild_id')

    op.drop_table('quests')
    op.drop_table('moderation_configs')
    with op.batch_alter_table('moderation_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_mod_actions_guild_user')
        batch_op.drop_index('ix_mod_actions_guild_type')

    op.drop_table('moderation_actions')
    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_help_conversations_user_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_user_id'))
        batch_op.drop_index('ix_help_conversations_tokens_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_started_at'))
        batch_op.drop_index('ix_help_conversations_session_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_is_sensitive'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_is_resolved'))
        batch_op.drop_index('ix_help_conversations_guild_started')
        batch_op.drop_index(batch_op.f('ix_help_conversations_guild_id'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_help_conversations_channel_id'))

    op.drop_table('help_conversations')
    with op.batch_alter_table('forum_user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_forum_user_subscriptions_user_id')
        batch_op.drop_index('ix_forum_user_subscriptions_guild_id')
        batch_op.drop_index('ix_forum_user_subscriptions_guild_forum')
        batch_op.drop_index('ix_forum_user_subscriptions_forum_channel_id')

    op.drop_table('forum_user_subscriptions')
    with op.batch_alter_table('forum_notification_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_forum_notification_topics_guild_id')
        batch_op.drop_index('ix_forum_notification_topics_guild_forum')
        batch_op.drop_index('ix_forum_notification_topics_forum_channel_id')

    op.drop_table('forum_notification_topics')
    with op.batch_alter_table('forum_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_agents_is_active'))
        batch_op.drop_index('ix_forum_agents_guild_id')
        batch_op.drop_index('ix_forum_agents_guild_active')
        batch_op.drop_index(batch_op.f('ix_forum_agents_enable_user_tagging'))
        batch_op.drop_index(batch_op.f('ix_forum_agents_enable_responses'))
        batch_op.drop_index('ix_forum_agents_created_by')

    op.drop_table('forum_agents')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_start_time')
        batch_op.drop_index(batch_op.f('ix_campaigns_is_active'))
        batch_op.drop_index('ix_campaigns_guild_id')
        batch_op.drop_index('ix_campaigns_guild_active')
        batch_op.drop_index('ix_campaigns_created_by')

    op.drop_table('campaigns')
    with op.batch_alter_table('campaign_signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_signups_confirmation_token'))
        batch_op.drop_index(batch_op.f('ix_campaign_signups_campaign_slug'))

    op.drop_table('campaign_signups')
    with op.batch_alter_table('bytes_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_bytes_transactions_receiver_id')
        batch_op.drop_index('ix_bytes_transactions_guild_receiver')
        batch_op.drop_index('ix_bytes_transactions_guild_id')
        batch_op.drop_index('ix_bytes_transactions_guild_giver')
        batch_op.drop_index('ix_bytes_transactions_giver_id')
        batch_op.drop_index('ix_bytes_transactions_created_at')

    op.drop_table('bytes_transactions')
    op.drop_table('bytes_configs')
    op.drop_table('bytes_balances')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_published_at'))
        batch_op.drop_index('ix_blog_posts_published')
        batch_op.drop_index(batch_op.f('ix_blog_posts_is_published'))
        batch_op.drop_index('ix_blog_posts_created_at')
        batch_op.drop_index('ix_blog_posts_author')

    op.drop_table('blog_posts')
    with op.batch_alter_table('audit_log_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_configs_guild_id')

    op.drop_table('audit_log_configs')
    with op.batch_alter_table('attachment_filter_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_attachment_filter_configs_guild_id')

    op.drop_table('attachment_filter_configs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_keys_prefix')
        batch_op.drop_index('ix_api_keys_hash')
        batch_op.drop_index('ix_api_keys_created_by')
        batch_op.drop_index('ix_api_keys_active', postgresql_where='is_active = true')

    op.drop_table('api_keys')
    op.drop_table('advent_of_code_configs')
    # ### end Alembic commands ###