"""Add forum agent tables for AI-powered forum monitoring

Revision ID: 3a5e58f6f94d
Revises: 530f4ea0d3d6
Create Date: 2025-08-08 19:14:22.112724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5e58f6f94d'
down_revision = '530f4ea0d3d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('monitored_forums', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('response_threshold', sa.Float(), nullable=False),
    sa.Column('max_responses_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_responses_per_hour >= 0', name=op.f('ck_forum_agents_ck_forum_agents_max_responses_positive')),
    sa.CheckConstraint('response_threshold >= 0.0 AND response_threshold <= 1.0', name=op.f('ck_forum_agents_ck_forum_agents_threshold_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_agents')),
    sa.UniqueConstraint('guild_id', 'name', name='uq_forum_agents_guild_name')
    )
    with op.batch_alter_table('forum_agents', schema=None) as batch_op:
        batch_op.create_index('ix_forum_agents_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_forum_agents_guild_active', ['guild_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agents_is_active'), ['is_active'], unique=False)

    op.create_table('forum_agent_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('post_title', sa.String(length=300), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('author_display_name', sa.String(length=100), nullable=False),
    sa.Column('post_tags', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_confidence_range')),
    sa.CheckConstraint('response_time_ms >= 0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_time_positive')),
    sa.CheckConstraint('tokens_used >= 0', name=op.f('ck_forum_agent_responses_ck_forum_agent_responses_tokens_positive')),
    sa.ForeignKeyConstraint(['agent_id'], ['forum_agents.id'], name=op.f('fk_forum_agent_responses_agent_id_forum_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_agent_responses'))
    )
    with op.batch_alter_table('forum_agent_responses', schema=None) as batch_op:
        batch_op.create_index('ix_forum_agent_responses_agent_created', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_channel_created', ['channel_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_guild_created', ['guild_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_responded'), ['responded'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_responded_at'), ['responded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_agent_responses_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_forum_agent_responses_tokens_created', ['tokens_used', 'created_at'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('blog_posts_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_posts_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_unique_constraint('uq_blog_posts_slug', ['slug'])

    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_conversations', schema=None) as batch_op:
        batch_op.drop_column('command_metadata')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_blog_posts_slug', type_='unique')
        batch_op.drop_index(batch_op.f('ix_blog_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_is_published'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('blog_posts_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)

    with op.batch_alter_table('forum_agent_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_forum_agent_responses_tokens_created')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_thread_id'))
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_responded_at'))
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_responded'))
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_guild_id'))
        batch_op.drop_index('ix_forum_agent_responses_guild_created')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_channel_id'))
        batch_op.drop_index('ix_forum_agent_responses_channel_created')
        batch_op.drop_index(batch_op.f('ix_forum_agent_responses_agent_id'))
        batch_op.drop_index('ix_forum_agent_responses_agent_created')

    op.drop_table('forum_agent_responses')
    with op.batch_alter_table('forum_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_agents_is_active'))
        batch_op.drop_index(batch_op.f('ix_forum_agents_guild_id'))
        batch_op.drop_index('ix_forum_agents_guild_active')
        batch_op.drop_index('ix_forum_agents_created_by')

    op.drop_table('forum_agents')
    # ### end Alembic commands ###