"""add_advent_of_code_tables

Revision ID: 3b4c5d6e7f8g
Revises: 2a3b4c5d6e7f
Create Date: 2025-11-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3b4c5d6e7f8g'
down_revision = '2a3b4c5d6e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create advent_of_code_configs table
    op.create_table('advent_of_code_configs',
        sa.Column('guild_id', sa.String(), nullable=False),
        sa.Column('forum_channel_id', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, default=False),
        sa.Column('year', sa.Integer(), nullable=False, default=2025),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_advent_of_code_configs'))
    )

    # Create advent_of_code_threads table
    op.create_table('advent_of_code_threads',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('guild_id', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('day', sa.Integer(), nullable=False),
        sa.Column('thread_id', sa.String(), nullable=False),
        sa.Column('thread_title', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['guild_id'], ['advent_of_code_configs.guild_id'], name=op.f('fk_advent_of_code_threads_guild_id_advent_of_code_configs'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_advent_of_code_threads')),
        sa.UniqueConstraint('guild_id', 'year', 'day', name='uq_aoc_thread_guild_year_day')
    )

    # Create indexes for advent_of_code_threads
    with op.batch_alter_table('advent_of_code_threads', schema=None) as batch_op:
        batch_op.create_index('ix_aoc_threads_guild_id', ['guild_id'], unique=False)
        batch_op.create_index('ix_aoc_threads_year_day', ['year', 'day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    with op.batch_alter_table('advent_of_code_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_aoc_threads_year_day')
        batch_op.drop_index('ix_aoc_threads_guild_id')

    # Drop tables
    op.drop_table('advent_of_code_threads')
    op.drop_table('advent_of_code_configs')

    # ### end Alembic commands ###
