"""Create initial database schema for Session 2

Revision ID: 597caa74eb23
Revises: 
Create Date: 2025-07-11 20:03:55.157861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597caa74eb23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###