"""add_attachment_filter_config_table

Revision ID: 5d6e7f8g9h0i
Revises: 4c5d6e7f8g9h
Create Date: 2025-12-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON


# revision identifiers, used by Alembic.
revision = '5d6e7f8g9h0i'
down_revision = '4c5d6e7f8g9h'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_filter_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('ignored_extensions', JSON(), nullable=False, server_default='[]'),
    sa.Column('warn_extensions', JSON(), nullable=False, server_default='[]'),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_attachment_filter_configs'))
    )
    with op.batch_alter_table('attachment_filter_configs', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_filter_configs_guild_id', ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment_filter_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_attachment_filter_configs_guild_id')

    op.drop_table('attachment_filter_configs')
    # ### end Alembic commands ###
