"""Remove campaign scheduled message fields and create ScheduledMessage table

Revision ID: 7b22e1920c66
Revises: c6ef6700c4b5
Create Date: 2025-08-14 16:04:14.184272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b22e1920c66'
down_revision = 'c6ef6700c4b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_time IS NOT NULL', name=op.f('ck_scheduled_messages_ck_scheduled_messages_time_required')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_scheduled_messages_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_messages'))
    )
    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_messages_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_scheduled_messages_campaign_time', ['campaign_id', 'scheduled_time'], unique=False)
        batch_op.create_index('ix_scheduled_messages_is_sent', ['is_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_messages_scheduled_time'), ['scheduled_time'], unique=False)
        batch_op.create_index('ix_scheduled_messages_sent_at', ['sent_at'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_is_scheduled_message_sent'))
        batch_op.drop_index(batch_op.f('ix_campaigns_scheduled_message_time'))
        batch_op.drop_column('scheduled_message_description')
        batch_op.drop_column('is_scheduled_message_sent')
        batch_op.drop_column('scheduled_message_time')
        batch_op.drop_column('scheduled_message_title')
        batch_op.drop_column('scheduled_message_sent_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_message_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_message_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_message_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_scheduled_message_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('scheduled_message_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_campaigns_scheduled_message_time'), ['scheduled_message_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_is_scheduled_message_sent'), ['is_scheduled_message_sent'], unique=False)

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_messages_sent_at')
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_scheduled_time'))
        batch_op.drop_index('ix_scheduled_messages_is_sent')
        batch_op.drop_index('ix_scheduled_messages_campaign_time')
        batch_op.drop_index(batch_op.f('ix_scheduled_messages_campaign_id'))

    op.drop_table('scheduled_messages')
    # ### end Alembic commands ###