"""Add challenge_submissions table for tracking solution submissions

Revision ID: 80956826a0eb
Revises: d04c2506b5af
Create Date: 2025-08-14 17:48:40.298376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80956826a0eb'
down_revision = 'd04c2506b5af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('submitted_solution', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_first_success', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_submissions_challenge_id_challenges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_challenge_submissions_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_submissions'))
    )
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenge_submissions_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index('ix_challenge_submissions_challenge_squad', ['challenge_id', 'squad_id'], unique=False)
        batch_op.create_index('ix_challenge_submissions_first_success', ['is_first_success', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_submissions_squad_id'), ['squad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challenge_submissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_challenge_submissions_user_submitted', ['user_id', 'submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_challenge_submissions_user_submitted')
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_squad_id'))
        batch_op.drop_index('ix_challenge_submissions_first_success')
        batch_op.drop_index('ix_challenge_submissions_challenge_squad')
        batch_op.drop_index(batch_op.f('ix_challenge_submissions_challenge_id'))

    op.drop_table('challenge_submissions')
    # ### end Alembic commands ###