"""Add released_at field to challenges table

Revision ID: e42a53a82aa4
Revises: 0bc598ce507e
Create Date: 2025-08-12 16:18:10.455285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42a53a82aa4'
down_revision = '0bc598ce507e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_challenges_campaign_released', ['campaign_id', 'released_at'], unique=False)
        batch_op.create_index('ix_challenges_released_at', ['released_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_challenges_released_at')
        batch_op.drop_index('ix_challenges_campaign_released')
        batch_op.drop_column('released_at')

    # ### end Alembic commands ###