"""add_is_default_field_to_squad_model

Revision ID: f252668f8bc3
Revises: 3a5e58f6f94d
Create Date: 2025-08-09 14:42:46.718923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f252668f8bc3'
down_revision = '3a5e58f6f94d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        # Add the is_default column with default value False
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
        
        # Add index for better query performance
        batch_op.create_index('ix_squads_guild_default', ['guild_id', 'is_default'])
        
        # Add unique constraint to ensure only one default squad per guild
        # Using raw SQL because batch_alter_table doesn't handle partial unique constraints well
    
    # Add the unique constraint with WHERE clause using raw SQL
    op.execute("""
        ALTER TABLE squads 
        ADD CONSTRAINT uq_squads_guild_default 
        UNIQUE (guild_id) 
        WHERE is_default = true
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unique constraint first
    op.drop_constraint('uq_squads_guild_default', 'squads', type_='unique')
    
    with op.batch_alter_table('squads', schema=None) as batch_op:
        # Drop index
        batch_op.drop_index('ix_squads_guild_default')
        
        # Drop column
        batch_op.drop_column('is_default')
    # ### end Alembic commands ###