"""add_audit_log_config_table

Revision ID: 2a3b4c5d6e7f
Revises: 1f214f10f9ba
Create Date: 2025-11-19 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3b4c5d6e7f'
down_revision = '1f214f10f9ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_configs',
    sa.Column('guild_id', sa.String(), nullable=False),
    sa.Column('audit_channel_id', sa.String(), nullable=True),
    sa.Column('log_member_join', sa.Boolean(), nullable=False),
    sa.Column('log_member_leave', sa.Boolean(), nullable=False),
    sa.Column('log_member_ban', sa.Boolean(), nullable=False),
    sa.Column('log_member_unban', sa.Boolean(), nullable=False),
    sa.Column('log_message_edit', sa.Boolean(), nullable=False),
    sa.Column('log_message_delete', sa.Boolean(), nullable=False),
    sa.Column('log_username_change', sa.Boolean(), nullable=False),
    sa.Column('log_nickname_change', sa.Boolean(), nullable=False),
    sa.Column('log_role_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_audit_log_configs'))
    )
    with op.batch_alter_table('audit_log_configs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_configs_guild_id', ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_configs_guild_id')

    op.drop_table('audit_log_configs')
    # ### end Alembic commands ###
