"""The signed-in user's dashboard at /dashboard, and its web search.

The sidebar holds Web search and Chat (``dashboard_nav``). ``/dashboard`` opens
the Quick chat for anyone with Chat, and the new-search view for everyone else.

The search pages are one shell that ``dashboard.js`` drives as a single-page
app: ``/dashboard/search``, ``/dashboard/search/{id}`` and ``/dashboard/browser``
all render it, with the view to open and everything it needs embedded, so a
reload paints at once.

A search runs in the agent-worker (``web_search_jobs``): ``POST
/dashboard/api/searches`` saves the row and hands it to the dispatch outbox,
then the worker notifies the owner over Skrift's SSE stream after every stage.
"""

from __future__ import annotations

import hashlib
import secrets
import time
from collections import defaultdict
from datetime import UTC
from datetime import datetime
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlencode
from uuid import UUID

from litestar import Controller
from litestar import Request
from litestar import delete
from litestar import get
from litestar import post
from litestar.exceptions import HTTPException
from litestar.response import Redirect
from litestar.response import Template
from litestar.status_codes import HTTP_201_CREATED
from msgspec import Struct
from skrift.auth.services import get_user_permissions
from skrift.auth.session_keys import SESSION_USER_ID
from skrift.db.models.user import User
from sqlalchemy import func
from sqlalchemy import or_
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from smarter_dev.shared.config import get_settings
from smarter_dev.web.chat.controller import quick_chat_page
from smarter_dev.web.chat.controller import rail_context
from smarter_dev.web.chat.csrf import require_api_csrf
from smarter_dev.web.chat.dispatch import create_dispatch
from smarter_dev.web.chat.dispatch import dispatch_one
from smarter_dev.web.chat.entitlements import has_chat
from smarter_dev.web.dashboard_nav import nav_context
from smarter_dev.web.dashboard_nav import recent_searches
from smarter_dev.web.models import UsageCostRow
from smarter_dev.web.models import WebSearchLink
from smarter_dev.web.models import WebSearchRun
from smarter_dev.web.user_content import StillRunning
from smarter_dev.web.user_content import delete_all_searches
from smarter_dev.web.user_content import delete_search
from smarter_dev.web.web_search.snapshot import EVENT_TYPE
from smarter_dev.web.web_search.snapshot import MAX_REQUEST_CHARS
from smarter_dev.web.web_search.snapshot import snapshot

MIN_REQUEST_CHARS = 3
# Each search costs five Brave queries, so both limits are per user.
PER_MINUTE_LIMIT = 6
PER_DAY_LIMIT = 100
_recent_starts: dict[str, list[float]] = defaultdict(list)


class LinkBody(Struct):
    open_addresses: bool | None = None
    # Replace the token: the old link stops working.
    rotate: bool = False


class SearchBody(Struct):
    request: str
    # Generated by the browser per submission, so a retried POST can't start
    # a second search.
    submission_key: str


THEME_DIR = Path(__file__).resolve().parents[2] / "themes" / "smarterdev"
CLIENT_FILES = (
    "static/js/dashboard.js",
    "static/js/dashboard-nav.js",
    "static/css/pages/user-dashboard.css",
    "static/css/pages/dashboard-nav.css",
    "templates/dashboard/index.html",
    "templates/dashboard/_nav.html",
)


def _client_build() -> str:
    """A fingerprint of the dashboard's page, script and styles. A tab open
    across a deploy sees a new one in an API reply and reloads, since the old
    script can't render what the new server sends."""
    digest = hashlib.sha256()
    for name in CLIENT_FILES:
        try:
            digest.update((THEME_DIR / name).read_bytes())
        except OSError:
            return ""
    return digest.hexdigest()[:12]


CLIENT_BUILD = _client_build()

def _session_user_id(request: Request) -> UUID | None:
    raw = request.session.get(SESSION_USER_ID) if request.session else None
    try:
        return UUID(str(raw)) if raw else None
    except ValueError:
        return None


async def _active_user(request: Request, db_session: AsyncSession) -> User:
    user_id = _session_user_id(request)
    user = await db_session.get(User, user_id) if user_id else None
    if user is None or not user.is_active:
        raise HTTPException(status_code=401, detail="Sign in to use the dashboard.")
    return user


def _login_redirect(request: Request) -> Redirect:
    return Redirect(
        path=f"/auth/login?{urlencode({'next': request.url.path})}", status_code=303
    )


async def _recent(db_session: AsyncSession, user_id: UUID) -> list[dict]:
    return await recent_searches(db_session, user_id)


async def _owned(db_session: AsyncSession, user_id: UUID, search_id: UUID) -> WebSearchRun:
    run = await db_session.get(WebSearchRun, search_id)
    if run is None or run.owner_user_id != user_id:
        raise HTTPException(status_code=404, detail="Search not found.")
    return run


def _validate_request(text: str) -> str:
    cleaned = " ".join((text or "").split())
    if len(cleaned) < MIN_REQUEST_CHARS:
        raise HTTPException(status_code=422, detail="Describe what you're looking for.")
    if len(cleaned) > MAX_REQUEST_CHARS:
        raise HTTPException(
            status_code=422,
            detail=f"Keep the search under {MAX_REQUEST_CHARS} characters.",
        )
    return cleaned


def _validate_submission_key(key: str) -> str:
    cleaned = (key or "").strip()
    if not 8 <= len(cleaned) <= 64 or not cleaned.replace("-", "").isalnum():
        raise HTTPException(status_code=422, detail="Invalid submission key.")
    return cleaned


async def _enforce_limits(db_session: AsyncSession, user_id: UUID) -> None:
    now = time.monotonic()
    starts = [t for t in _recent_starts[str(user_id)] if now - t < 60]
    if len(starts) >= PER_MINUTE_LIMIT:
        raise HTTPException(
            status_code=429, detail="That's a lot of searches. Try again in a minute."
        )
    today = await searches_in_last_day(db_session, user_id)
    if today >= PER_DAY_LIMIT:
        raise HTTPException(
            status_code=429,
            detail=f"You've run {PER_DAY_LIMIT} searches in the last day. Try again later.",
        )
    _recent_starts[str(user_id)] = [*starts, now]


async def searches_in_last_day(db_session: AsyncSession, user_id: UUID) -> int:
    """Searches started in the last day, deleted ones included.

    A deleted search's cost rows stay, naming it, so deleting searches does not
    reset the daily limit. Searches run through the member's search link while
    signed out are charged to them too, but are not theirs to count.
    """
    since = datetime.now(UTC) - timedelta(days=1)
    started = set(
        (
            await db_session.execute(
                select(WebSearchRun.id).where(
                    WebSearchRun.owner_user_id == user_id, WebSearchRun.created_at >= since
                )
            )
        ).scalars()
    )
    # A search was started when it was first charged; a retry billed later is
    # not a new search.
    charged = (
        set(
            (
                await db_session.execute(
                    select(UsageCostRow.root_turn_id)
                    .where(
                        UsageCostRow.user_id == user_id,
                        UsageCostRow.product_mode == "search",
                        UsageCostRow.root_turn_id.is_not(None),
                        or_(
                            UsageCostRow.details["anonymous"].as_boolean().is_(None),
                            UsageCostRow.details["anonymous"].as_boolean().is_(False),
                        ),
                    )
                    .group_by(UsageCostRow.root_turn_id)
                    .having(func.min(UsageCostRow.metered_at) >= since)
                )
            ).scalars()
        )
        - started
    )
    if charged:
        charged -= set(
            (
                await db_session.execute(
                    select(WebSearchRun.id).where(WebSearchRun.id.in_(charged))
                )
            ).scalars()
        )
    return len(started) + len(charged)


def link_state(link: WebSearchLink | None) -> dict | None:
    """The user's search link as the dashboard shows it."""
    if link is None:
        return None
    base = get_settings().site_base_url.rstrip("/")
    return {
        "url": f"{base}/s/{link.token}?q=%s",
        "opensearch": f"/s/{link.token}/opensearch.xml",
        "open_addresses": link.open_addresses,
    }


async def _link(db_session: AsyncSession, user_id: UUID) -> WebSearchLink | None:
    return await db_session.scalar(
        select(WebSearchLink).where(WebSearchLink.owner_user_id == user_id)
    )


def new_link_token() -> str:
    return secrets.token_urlsafe(18)


async def create_search(
    db_session: AsyncSession, user_id: UUID, text: str, submission_key: str
) -> WebSearchRun:
    """Save a new search and hand it to the agent-worker."""
    run = WebSearchRun(
        owner_user_id=user_id,
        submission_key=submission_key,
        request=text,
        status="queued",
        queries=[],
        results=[],
        ranked=False,
        usage={},
        version=0,
        attempt_count=0,
    )
    db_session.add(run)
    await db_session.flush()
    dispatch = await create_dispatch(
        db_session,
        job_type="web_search.run",
        aggregate_id=run.id,
        payload={"search_id": str(run.id)},
    )
    await db_session.commit()
    await db_session.refresh(run)
    try:
        await dispatch_one(dispatch.id)
    except Exception:  # noqa: BLE001 - the outbox reconciler retries it
        pass
    return run


class DashboardController(Controller):
    path = "/dashboard"

    async def _page(
        self,
        request: Request,
        db_session: AsyncSession,
        search_id: UUID | None,
        view: str | None = None,
    ) -> Template | Redirect:
        user_id = _session_user_id(request)
        user = await db_session.get(User, user_id) if user_id else None
        if user is None or not user.is_active:
            return _login_redirect(request)
        permissions = await get_user_permissions(db_session, user.id)
        chat = has_chat(permissions)
        if view == "default":
            if chat:
                return await quick_chat_page(db_session, user.id, permissions)
            view = None
        search = None
        if search_id is not None:
            run = await db_session.get(WebSearchRun, search_id)
            if run is None or run.owner_user_id != user.id:
                raise HTTPException(status_code=404, detail="Search not found.")
            search = snapshot(run)
        view = view or ("search" if search else "home")
        recent = await _recent(db_session, user.id)
        return Template(
            "dashboard/index.html",
            context={
                **nav_context(
                    page="dashboard",
                    open_section="search",
                    recent=recent,
                    chat=chat,
                    tool=None if search else view if view == "browser" else "search",
                    search_id=search["id"] if search else None,
                ),
                **(await rail_context(db_session, user.id) if chat else {}),
                "dashboard_state": {
                    "view": view,
                    # /dashboard is the Quick chat for this user, not the
                    # new-search view, so going back to it needs the server.
                    "chat_home": chat,
                    "user": {"name": user.name or "there"},
                    "recent": recent,
                    "search": search,
                    "event_type": EVENT_TYPE,
                    "max_request_chars": MAX_REQUEST_CHARS,
                    "build": CLIENT_BUILD,
                    "link": link_state(await _link(db_session, user.id)),
                },
                "seo_meta": {"robots": "noindex,nofollow", "description": "Your Smarter Dev dashboard"},
            },
        )

    @get("/")
    async def home(self, request: Request, db_session: AsyncSession) -> Template | Redirect:
        return await self._page(request, db_session, None, view="default")

    @get("/search")
    async def new_search_page(
        self, request: Request, db_session: AsyncSession
    ) -> Template | Redirect:
        return await self._page(request, db_session, None)

    @get("/search/{search_id:uuid}")
    async def search_page(
        self, request: Request, db_session: AsyncSession, search_id: UUID
    ) -> Template | Redirect:
        return await self._page(request, db_session, search_id)

    @get("/browser")
    async def browser_page(self, request: Request, db_session: AsyncSession) -> Template | Redirect:
        return await self._page(request, db_session, None, view="browser")

    @get("/api/link")
    async def get_link(self, request: Request, db_session: AsyncSession) -> dict:
        user = await _active_user(request, db_session)
        return {"link": link_state(await _link(db_session, user.id)), "build": CLIENT_BUILD}

    @post("/api/link", status_code=200)
    async def save_link(self, data: LinkBody, request: Request, db_session: AsyncSession) -> dict:
        """Create the user's search link, or change its options or token."""
        require_api_csrf(request)
        user = await _active_user(request, db_session)
        link = await _link(db_session, user.id)
        if link is None:
            link = WebSearchLink(
                owner_user_id=user.id, token=new_link_token(), open_addresses=False
            )
            db_session.add(link)
        elif data.rotate:
            link.token = new_link_token()
        if data.open_addresses is not None:
            link.open_addresses = data.open_addresses
        await db_session.commit()
        return {"link": link_state(link), "build": CLIENT_BUILD}

    @delete("/api/link", status_code=200)
    async def delete_link(self, request: Request, db_session: AsyncSession) -> dict:
        require_api_csrf(request)
        user = await _active_user(request, db_session)
        link = await _link(db_session, user.id)
        if link is not None:
            await db_session.delete(link)
            await db_session.commit()
        return {"link": None, "build": CLIENT_BUILD}

    @get("/api/searches")
    async def list_searches(self, request: Request, db_session: AsyncSession) -> dict:
        user = await _active_user(request, db_session)
        return {"searches": await _recent(db_session, user.id), "build": CLIENT_BUILD}

    @get("/api/searches/{search_id:uuid}")
    async def get_search(
        self, request: Request, db_session: AsyncSession, search_id: UUID
    ) -> dict:
        user = await _active_user(request, db_session)
        return {
            "search": snapshot(await _owned(db_session, user.id, search_id)),
            "build": CLIENT_BUILD,
        }

    @delete("/api/searches/{search_id:uuid}", status_code=200)
    async def delete_one_search(
        self, request: Request, db_session: AsyncSession, search_id: UUID
    ) -> dict:
        require_api_csrf(request)
        user = await _active_user(request, db_session)
        try:
            await delete_search(db_session, await _owned(db_session, user.id, search_id))
        except StillRunning:
            raise HTTPException(
                status_code=409, detail="Wait for this search to finish, then delete it."
            ) from None
        return {"searches": await _recent(db_session, user.id), "build": CLIENT_BUILD}

    @delete("/api/searches", status_code=200)
    async def delete_every_search(self, request: Request, db_session: AsyncSession) -> dict:
        require_api_csrf(request)
        user = await _active_user(request, db_session)
        result = await delete_all_searches(db_session, user.id)
        return {
            "deleted": result.deleted,
            "running": result.running,
            "searches": await _recent(db_session, user.id),
            "build": CLIENT_BUILD,
        }

    @post("/api/searches", status_code=HTTP_201_CREATED)
    async def start_search(
        self, data: SearchBody, request: Request, db_session: AsyncSession
    ) -> dict:
        require_api_csrf(request)
        user = await _active_user(request, db_session)
        submission_key = _validate_submission_key(data.submission_key)
        existing = await db_session.scalar(
            select(WebSearchRun).where(
                WebSearchRun.owner_user_id == user.id,
                WebSearchRun.submission_key == submission_key,
            )
        )
        if existing is not None:
            return {"search": snapshot(existing), "idempotent": True, "build": CLIENT_BUILD}
        text = _validate_request(data.request)
        await _enforce_limits(db_session, user.id)
        run = await create_search(db_session, user.id, text, submission_key)
        return {"search": snapshot(run), "build": CLIENT_BUILD}
