"""The signed-in user's dashboard at /dashboard, and its web search.

The page is one shell that ``dashboard.js`` drives as a single-page app:
``/dashboard`` and ``/dashboard/search/{id}`` both render it, with the view
to open and everything it needs embedded, so a reload paints at once.

A search runs in the agent-worker (``web_search_jobs``): ``POST
/dashboard/api/searches`` saves the row and hands it to the dispatch outbox,
then the worker notifies the owner over Skrift's SSE stream after every stage.
"""

from __future__ import annotations

import hashlib
import time
from collections import defaultdict
from datetime import UTC
from datetime import datetime
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlencode
from uuid import UUID

from litestar import Controller
from litestar import Request
from litestar import get
from litestar import post
from litestar.exceptions import HTTPException
from litestar.response import Redirect
from litestar.response import Template
from litestar.status_codes import HTTP_201_CREATED
from msgspec import Struct
from skrift.auth.session_keys import SESSION_USER_ID
from skrift.db.models.user import User
from sqlalchemy import func
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from smarter_dev.web.chat.csrf import require_api_csrf
from smarter_dev.web.chat.dispatch import create_dispatch
from smarter_dev.web.chat.dispatch import dispatch_one
from smarter_dev.web.models import WebSearchRun
from smarter_dev.web.web_search.snapshot import EVENT_TYPE
from smarter_dev.web.web_search.snapshot import MAX_REQUEST_CHARS
from smarter_dev.web.web_search.snapshot import snapshot
from smarter_dev.web.web_search.snapshot import summary

RECENT_LIMIT = 20
MIN_REQUEST_CHARS = 3
# Each search costs five Brave queries, so both limits are per user.
PER_MINUTE_LIMIT = 6
PER_DAY_LIMIT = 100
_recent_starts: dict[str, list[float]] = defaultdict(list)


class SearchBody(Struct):
    request: str
    # Generated by the browser per submission, so a retried POST can't start
    # a second search.
    submission_key: str


THEME_DIR = Path(__file__).resolve().parents[2] / "themes" / "smarterdev"
CLIENT_FILES = (
    "static/js/dashboard.js",
    "static/css/pages/user-dashboard.css",
    "templates/dashboard/index.html",
)


def _client_build() -> str:
    """A fingerprint of the dashboard's page, script and styles. A tab open
    across a deploy sees a new one in an API reply and reloads, since the old
    script can't render what the new server sends."""
    digest = hashlib.sha256()
    for name in CLIENT_FILES:
        try:
            digest.update((THEME_DIR / name).read_bytes())
        except OSError:
            return ""
    return digest.hexdigest()[:12]


CLIENT_BUILD = _client_build()

def _session_user_id(request: Request) -> UUID | None:
    raw = request.session.get(SESSION_USER_ID) if request.session else None
    try:
        return UUID(str(raw)) if raw else None
    except ValueError:
        return None


async def _active_user(request: Request, db_session: AsyncSession) -> User:
    user_id = _session_user_id(request)
    user = await db_session.get(User, user_id) if user_id else None
    if user is None or not user.is_active:
        raise HTTPException(status_code=401, detail="Sign in to use the dashboard.")
    return user


def _login_redirect(request: Request) -> Redirect:
    return Redirect(
        path=f"/auth/login?{urlencode({'next': request.url.path})}", status_code=303
    )


async def _recent(db_session: AsyncSession, user_id: UUID) -> list[dict]:
    rows = await db_session.scalars(
        select(WebSearchRun)
        .where(WebSearchRun.owner_user_id == user_id)
        .order_by(WebSearchRun.created_at.desc())
        .limit(RECENT_LIMIT)
    )
    return [summary(row) for row in rows]


async def _owned(db_session: AsyncSession, user_id: UUID, search_id: UUID) -> WebSearchRun:
    run = await db_session.get(WebSearchRun, search_id)
    if run is None or run.owner_user_id != user_id:
        raise HTTPException(status_code=404, detail="Search not found.")
    return run


def _validate_request(text: str) -> str:
    cleaned = " ".join((text or "").split())
    if len(cleaned) < MIN_REQUEST_CHARS:
        raise HTTPException(status_code=422, detail="Describe what you're looking for.")
    if len(cleaned) > MAX_REQUEST_CHARS:
        raise HTTPException(
            status_code=422,
            detail=f"Keep the search under {MAX_REQUEST_CHARS} characters.",
        )
    return cleaned


def _validate_submission_key(key: str) -> str:
    cleaned = (key or "").strip()
    if not 8 <= len(cleaned) <= 64 or not cleaned.replace("-", "").isalnum():
        raise HTTPException(status_code=422, detail="Invalid submission key.")
    return cleaned


async def _enforce_limits(db_session: AsyncSession, user_id: UUID) -> None:
    now = time.monotonic()
    starts = [t for t in _recent_starts[str(user_id)] if now - t < 60]
    if len(starts) >= PER_MINUTE_LIMIT:
        raise HTTPException(
            status_code=429, detail="That's a lot of searches. Try again in a minute."
        )
    today = await db_session.scalar(
        select(func.count())
        .select_from(WebSearchRun)
        .where(
            WebSearchRun.owner_user_id == user_id,
            WebSearchRun.created_at >= datetime.now(UTC) - timedelta(days=1),
        )
    )
    if (today or 0) >= PER_DAY_LIMIT:
        raise HTTPException(
            status_code=429,
            detail=f"You've run {PER_DAY_LIMIT} searches in the last day. Try again later.",
        )
    _recent_starts[str(user_id)] = [*starts, now]


class DashboardController(Controller):
    path = "/dashboard"

    async def _page(
        self, request: Request, db_session: AsyncSession, search_id: UUID | None
    ) -> Template | Redirect:
        user_id = _session_user_id(request)
        user = await db_session.get(User, user_id) if user_id else None
        if user is None or not user.is_active:
            return _login_redirect(request)
        search = None
        if search_id is not None:
            run = await db_session.get(WebSearchRun, search_id)
            if run is None or run.owner_user_id != user.id:
                raise HTTPException(status_code=404, detail="Search not found.")
            search = snapshot(run)
        return Template(
            "dashboard/index.html",
            context={
                "dashboard_state": {
                    "view": "search" if search else "home",
                    "user": {"name": user.name or "there"},
                    "recent": await _recent(db_session, user.id),
                    "search": search,
                    "event_type": EVENT_TYPE,
                    "max_request_chars": MAX_REQUEST_CHARS,
                    "build": CLIENT_BUILD,
                },
                "seo_meta": {"robots": "noindex,nofollow", "description": "Your Smarter Dev dashboard"},
            },
        )

    @get("/")
    async def home(self, request: Request, db_session: AsyncSession) -> Template | Redirect:
        return await self._page(request, db_session, None)

    @get("/search/{search_id:uuid}")
    async def search_page(
        self, request: Request, db_session: AsyncSession, search_id: UUID
    ) -> Template | Redirect:
        return await self._page(request, db_session, search_id)

    @get("/api/searches")
    async def list_searches(self, request: Request, db_session: AsyncSession) -> dict:
        user = await _active_user(request, db_session)
        return {"searches": await _recent(db_session, user.id), "build": CLIENT_BUILD}

    @get("/api/searches/{search_id:uuid}")
    async def get_search(
        self, request: Request, db_session: AsyncSession, search_id: UUID
    ) -> dict:
        user = await _active_user(request, db_session)
        return {
            "search": snapshot(await _owned(db_session, user.id, search_id)),
            "build": CLIENT_BUILD,
        }

    @post("/api/searches", status_code=HTTP_201_CREATED)
    async def start_search(
        self, data: SearchBody, request: Request, db_session: AsyncSession
    ) -> dict:
        require_api_csrf(request)
        user = await _active_user(request, db_session)
        submission_key = _validate_submission_key(data.submission_key)
        existing = await db_session.scalar(
            select(WebSearchRun).where(
                WebSearchRun.owner_user_id == user.id,
                WebSearchRun.submission_key == submission_key,
            )
        )
        if existing is not None:
            return {"search": snapshot(existing), "idempotent": True, "build": CLIENT_BUILD}
        text = _validate_request(data.request)
        await _enforce_limits(db_session, user.id)
        run = WebSearchRun(
            owner_user_id=user.id,
            submission_key=submission_key,
            request=text,
            status="queued",
            queries=[],
            results=[],
            ranked=False,
            usage={},
            version=0,
            attempt_count=0,
        )
        db_session.add(run)
        await db_session.flush()
        dispatch = await create_dispatch(
            db_session,
            job_type="web_search.run",
            aggregate_id=run.id,
            payload={"search_id": str(run.id)},
        )
        await db_session.commit()
        await db_session.refresh(run)
        try:
            await dispatch_one(dispatch.id)
        except Exception:  # noqa: BLE001 - the outbox reconciler retries it
            pass
        return {"search": snapshot(run), "build": CLIENT_BUILD}
