"""Curated content for /resources/production-operations.

The Keep-it-healthy layer of the resources index. Pairs with
/resources/system-architecture (the What) and /resources/infrastructure-hosting
(the Where).
"""

from __future__ import annotations

from datetime import date

from smarter_dev.web.system_architecture_data import (
    ArchCategory,
    ArchResource,
    ArchTool,
    ArchToolResource,
)
from smarter_dev.web.vibe_courses_data import FAQ, Person

_INDEXED = date(2026, 5, 12)


def _r(title, url, source, key, tool_slugs, learning_type, blurb=""):
    return ArchToolResource(
        title=title, url=url, source=source, key=key,
        tool_slugs=tuple(tool_slugs), learning_type=learning_type,
        first_indexed_at=_INDEXED, blurb=blurb,
    )


def _s(title, url, source, key, learning_type, blurb=""):
    return ArchResource(
        title=title, url=url, source=source, key=key,
        learning_type=learning_type, first_indexed_at=_INDEXED, blurb=blurb,
    )


# ─── CATEGORIES ──────────────────────────────────────────────────────────────

OPS_CATEGORIES: list[ArchCategory] = [
    ArchCategory(
        slug="observability",
        name="Observability",
        intro=(
            "The three pillars (metrics, logs, traces) are a taxonomy, not a "
            "plan. What you want is structured events you can slice "
            "arbitrarily: OpenTelemetry to instrument, plus a backend that "
            "handles high-cardinality (Honeycomb, Logfire) or a predictable "
            "metrics stack (Prometheus + Grafana + Loki). Start with one "
            "signal you'll actually look at. What to instrument is a design "
            "decision (see "
            "<a href=\"/resources/system-architecture\">System Architecture</a>); "
            "this list is about the tools that store and query what you've chosen."
        ),
        tools=(
            ArchTool("prometheus", "Prometheus",
                     "https://prometheus.io/",
                     "ops:tool:prometheus:home",
                     "Pull-based metrics collection. Deeply integrated with the Kubernetes ecosystem."),
            ArchTool("grafana", "Grafana",
                     "https://grafana.com/",
                     "ops:tool:grafana:home",
                     "Dashboard tool that fronts Prometheus, Loki, and most observability backends."),
            ArchTool("opentelemetry", "OpenTelemetry",
                     "https://opentelemetry.io/",
                     "ops:tool:opentelemetry:home",
                     "Vendor-neutral instrumentation standard for traces, metrics, and logs."),
            ArchTool("loki", "Grafana Loki",
                     "https://grafana.com/oss/loki/",
                     "ops:tool:loki:home",
                     "Log aggregation system designed to pair with Prometheus and Grafana."),
            ArchTool("tempo", "Grafana Tempo",
                     "https://grafana.com/oss/tempo/",
                     "ops:tool:tempo:home",
                     "Grafana's distributed tracing backend. Pairs with Loki and Mimir as the LGTM stack."),
            ArchTool("mimir", "Grafana Mimir",
                     "https://grafana.com/oss/mimir/",
                     "ops:tool:mimir:home",
                     "Horizontally-scalable Prometheus-compatible metrics backend for very large deployments."),
            ArchTool("logfire", "Pydantic Logfire",
                     "https://pydantic.dev/logfire",
                     "ops:tool:logfire:home",
                     "Observability platform from the Pydantic team. Structured tracing, OpenTelemetry-native."),
            ArchTool("honeycomb", "Honeycomb",
                     "https://www.honeycomb.io/",
                     "ops:tool:honeycomb:home",
                     "High-cardinality structured-event observability. Pioneered the \"observability 2.0\" frame."),
            ArchTool("datadog", "Datadog",
                     "https://www.datadoghq.com/",
                     "ops:tool:datadog:home",
                     "The commercial heavyweight. Observability plus APM plus security, with pricing to match."),
            ArchTool("sentry", "Sentry",
                     "https://sentry.io/",
                     "ops:tool:sentry:home",
                     "Error and performance monitoring. The default for catching frontend and backend exceptions."),
            ArchTool("new-relic", "New Relic",
                     "https://newrelic.com/",
                     "ops:tool:new-relic:home",
                     "Long-time APM vendor reorganized around usage-based pricing and a single observability platform."),
            ArchTool("better-stack", "Better Stack",
                     "https://betterstack.com/",
                     "ops:tool:better-stack:home",
                     "Combined logs, uptime, and dashboards in one commercial offering. Lightweight pricing."),
            ArchTool("axiom", "Axiom",
                     "https://axiom.co/",
                     "ops:tool:axiom:home",
                     "Log management and analytics with structured-event focus. The cheap-for-volume alternative."),
            ArchTool("signoz", "SigNoz",
                     "https://signoz.io/",
                     "ops:tool:signoz:home",
                     "Open-source full observability platform. The Datadog alternative if you want to self-host."),
        ),
    ),
    ArchCategory(
        slug="incident-response",
        name="Incident response & alerting",
        intro=(
            "The page going off at 3 AM is one piece. The other pieces are "
            "knowing who responds, what runbook they follow, how the team "
            "coordinates during the incident, what gets fixed afterward, "
            "and how customers find out. PagerDuty and Opsgenie are the "
            "legacy defaults; FireHydrant and Incident.io are the new wave "
            "with deeper opinions about coordination. Statuspage handles "
            "the outward-facing part."
        ),
        tools=(
            ArchTool("pagerduty", "PagerDuty",
                     "https://www.pagerduty.com/",
                     "ops:tool:pagerduty:home",
                     "The original on-call platform. Deepest integration ecosystem; expensive at scale."),
            ArchTool("opsgenie", "Opsgenie",
                     "https://www.atlassian.com/software/opsgenie",
                     "ops:tool:opsgenie:home",
                     "Atlassian's PagerDuty competitor. Strong if you're already in the Atlassian stack."),
            ArchTool("grafana-oncall", "Grafana OnCall",
                     "https://grafana.com/products/oncall/",
                     "ops:tool:grafana-oncall:home",
                     "OSS on-call scheduling. Pairs cleanly with Grafana Alertmanager."),
            ArchTool("firehydrant", "FireHydrant",
                     "https://firehydrant.com/",
                     "ops:tool:firehydrant:home",
                     "Incident response with strong runbook automation and Slack coordination."),
            ArchTool("incident-io", "Incident.io",
                     "https://incident.io/",
                     "ops:tool:incident-io:home",
                     "Slack-native incident management; opinionated about coordination patterns."),
            ArchTool("statuspage", "Atlassian Statuspage",
                     "https://www.atlassian.com/software/statuspage",
                     "ops:tool:statuspage:home",
                     "The outward-facing status-communication standard."),
            ArchTool("better-stack-incident", "Better Stack (incident management)",
                     "https://betterstack.com/incident-management",
                     "ops:tool:better-stack-incident:home",
                     "Combined uptime, on-call rotations, and status page in one lightweight offering."),
        ),
    ),
    ArchCategory(
        slug="logging",
        name="Logging pipelines",
        intro=(
            "Shipping logs from your servers to your backend is its own "
            "discipline. Vector and Fluent Bit dominate the open-source "
            "side. Fluentd is the older sibling that's still widely "
            "deployed. Cribl is the commercial heavyweight when you need "
            "to filter, transform, or route to multiple backends. The "
            "choice is usually about throughput and how much processing "
            "you want at the edge before logs hit storage."
        ),
        tools=(
            ArchTool("vector", "Vector",
                     "https://vector.dev/",
                     "ops:tool:vector:home",
                     "Datadog's Rust-based log and metric pipeline. The high-performance default for modern stacks."),
            ArchTool("fluent-bit", "Fluent Bit",
                     "https://fluentbit.io/",
                     "ops:tool:fluent-bit:home",
                     "Lightweight log collector and forwarder. The OpenTelemetry-adjacent default in Kubernetes."),
            ArchTool("fluentd", "Fluentd",
                     "https://www.fluentd.org/",
                     "ops:tool:fluentd:home",
                     "The older Ruby + C log aggregator. Still widely deployed; broader plugin ecosystem."),
            ArchTool("bento", "Bento",
                     "https://warpstreamlabs.github.io/bento/",
                     "ops:tool:bento:home",
                     "Stream-processing toolkit (formerly Benthos). Filter, transform, and route at the edge."),
            ArchTool("cribl", "Cribl Stream",
                     "https://cribl.io/stream/",
                     "ops:tool:cribl:home",
                     "Commercial heavyweight for routing logs to many backends with filter, transform, and replay."),
        ),
    ),
    ArchCategory(
        slug="performance",
        name="Performance & profiling",
        intro=(
            "Performance is the discipline observability won't teach you. "
            "Metrics tell you something's slow. Profiles tell you why. "
            "Tools split into continuous profiling (always running, "
            "sampling) and on-demand profiling (you reach for them during "
            "an incident). eBPF unlocks the kernel-level view that used "
            "to be a Brendan Gregg exclusive."
        ),
        tools=(
            ArchTool("pyroscope", "Grafana Pyroscope",
                     "https://grafana.com/oss/pyroscope/",
                     "ops:tool:pyroscope:home",
                     "Grafana's continuous profiling backend. eBPF-powered, language-agnostic."),
            ArchTool("parca", "Parca",
                     "https://www.parca.dev/",
                     "ops:tool:parca:home",
                     "OSS continuous profiling. Polar Signals' open-source foundation."),
            ArchTool("polar-signals", "Polar Signals",
                     "https://www.polarsignals.com/",
                     "ops:tool:polar-signals:home",
                     "Continuous profiling as a service. Pyroscope-compatible, hosted offering."),
            ArchTool("pixie", "Pixie",
                     "https://px.dev/",
                     "ops:tool:pixie:home",
                     "eBPF-based observability for Kubernetes. Auto-instrumented; no code changes."),
            ArchTool("datadog-profiler", "Datadog Continuous Profiler",
                     "https://docs.datadoghq.com/profiler/",
                     "ops:tool:datadog-profiler:home",
                     "Datadog's profiling product, deeply integrated with their APM and request tracing."),
            ArchTool("perf-flamegraph", "perf / flamegraph",
                     "https://www.brendangregg.com/flamegraphs.html",
                     "ops:tool:perf-flamegraph:home",
                     "Brendan Gregg's flamegraph tooling. The Linux profiling stack practitioners reach for."),
            ArchTool("bpftrace", "BCC / bpftrace",
                     "https://github.com/iovisor/bpftrace",
                     "ops:tool:bpftrace:home",
                     "eBPF-based dynamic tracing. Kernel-level visibility without recompiling the kernel."),
        ),
    ),
    ArchCategory(
        slug="identity",
        name="Identity & auth",
        intro=(
            "Auth is one of the few things worth outsourcing early. Auth0 "
            "if you need it now. Clerk and WorkOS are the new generation "
            "with better B2B ergonomics. Keycloak or Ory if you self-host. "
            "Supertokens, FusionAuth, and Logto are the lighter-weight "
            "self-hostable options. Decision is usually how much B2B "
            "complexity you have (SAML, SCIM, RBAC) and how much you want "
            "to pay someone else to manage it. The choice of how much "
            "identity you build into your domain model is an API decision "
            "(see "
            "<a href=\"/resources/system-architecture#apis\">APIs &amp; protocols</a>); "
            "this section is about who runs identity for you."
        ),
        tools=(
            ArchTool("auth0", "Auth0",
                     "https://auth0.com/",
                     "ops:tool:auth0:home",
                     "Managed identity-as-a-service. Fastest to integrate; expensive at scale."),
            ArchTool("clerk", "Clerk",
                     "https://clerk.com/",
                     "ops:tool:clerk:home",
                     "Developer-first auth-as-a-service. Excellent React/Next.js story and UI components."),
            ArchTool("workos", "WorkOS",
                     "https://workos.com/",
                     "ops:tool:workos:home",
                     "B2B-first auth: SSO, SCIM, audit logs. The \"enterprise-ready\" middleware."),
            ArchTool("stytch", "Stytch",
                     "https://stytch.com/",
                     "ops:tool:stytch:home",
                     "Passwordless-first auth platform. Strong on email magic links and B2B SSO."),
            ArchTool("keycloak", "Keycloak",
                     "https://www.keycloak.org/",
                     "ops:tool:keycloak:home",
                     "Self-hostable identity and access management. Full OAuth, OIDC, SAML support."),
            ArchTool("ory", "Ory",
                     "https://www.ory.sh/",
                     "ops:tool:ory:home",
                     "Modern OSS identity stack split into composable services (Kratos, Hydra, Oathkeeper)."),
            ArchTool("supertokens", "Supertokens",
                     "https://supertokens.com/",
                     "ops:tool:supertokens:home",
                     "Self-hostable auth library. Open source, modern, language-agnostic."),
            ArchTool("fusionauth", "FusionAuth",
                     "https://fusionauth.io/",
                     "ops:tool:fusionauth:home",
                     "Self-hostable auth platform. Generous free tier; deep CIAM features."),
            ArchTool("logto", "Logto",
                     "https://logto.io/",
                     "ops:tool:logto:home",
                     "Modern OSS auth and identity platform. The lighter alternative to Keycloak."),
        ),
    ),
    ArchCategory(
        slug="secrets",
        name="Secrets management",
        intro=(
            "Everyone outgrows .env files. The question is where you go "
            "next. Cloud-native secrets managers (AWS, GCP, Azure) win on "
            "integration if you're already in that cloud. Vault is the "
            "heavyweight when you need dynamic credentials and deep audit. "
            "Doppler and Infisical are the modern alternatives with better "
            "DX. SOPS and age handle the \"encrypt at rest, decrypt at "
            "deploy\" pattern for Git-backed secrets. Wiring secrets "
            "through your pipeline is a delivery concern (see "
            "<a href=\"/resources/software-delivery#cicd\">Software Delivery</a>)."
        ),
        tools=(
            ArchTool("vault", "HashiCorp Vault",
                     "https://www.vaultproject.io/",
                     "ops:tool:vault:home",
                     "Secrets management: dynamic credentials, encryption-as-a-service, deep audit."),
            ArchTool("aws-secrets-manager", "AWS Secrets Manager",
                     "https://aws.amazon.com/secrets-manager/",
                     "ops:tool:aws-secrets-manager:home",
                     "AWS-native secrets storage with rotation. Deep IAM integration if you're in AWS."),
            ArchTool("gcp-secret-manager", "Google Cloud Secret Manager",
                     "https://cloud.google.com/secret-manager",
                     "ops:tool:gcp-secret-manager:home",
                     "GCP-native secrets storage. Versioned, IAM-controlled, integrated with Cloud Build."),
            ArchTool("1password-secrets", "1Password Secrets Automation",
                     "https://1password.com/developers",
                     "ops:tool:1password-secrets:home",
                     "1Password for app secrets. Strong developer UX; CLI + service tokens for CI."),
            ArchTool("doppler", "Doppler",
                     "https://www.doppler.com/",
                     "ops:tool:doppler:home",
                     "Modern secrets manager with team workflows. Sync to most platforms."),
            ArchTool("infisical", "Infisical",
                     "https://infisical.com/",
                     "ops:tool:infisical:home",
                     "Open-source Doppler alternative. Self-hostable, modern UI, growing ecosystem."),
            ArchTool("sops", "SOPS",
                     "https://getsops.io/",
                     "ops:tool:sops:home",
                     "Mozilla's secret-encryption tool. Encrypt YAML/JSON files in Git."),
            ArchTool("age", "age",
                     "https://github.com/FiloSottile/age",
                     "ops:tool:age:home",
                     "Modern file encryption tool. The cryptographic primitive under SOPS and many others."),
        ),
    ),
    ArchCategory(
        slug="network-security",
        name="Network security & firewalls",
        intro=(
            "The perimeter is everywhere. WAFs (Cloudflare, AWS) handle "
            "the edge. Host firewalls (iptables, nftables, ufw) handle "
            "the server. mTLS and service-mesh policies handle "
            "service-to-service. Let's Encrypt handles TLS certificates. "
            "Each layer is mandatory if you care about the layer beneath."
        ),
        tools=(
            ArchTool("cloudflare-waf", "Cloudflare WAF",
                     "https://www.cloudflare.com/application-services/products/waf/",
                     "ops:tool:cloudflare-waf:home",
                     "Edge WAF rules. The default for most teams already behind Cloudflare."),
            ArchTool("aws-waf", "AWS WAF",
                     "https://aws.amazon.com/waf/",
                     "ops:tool:aws-waf:home",
                     "AWS's WAF for CloudFront, ALB, and API Gateway. AWS-native rules and managed rule groups."),
            ArchTool("gcp-armor", "Google Cloud Armor",
                     "https://cloud.google.com/security/products/armor",
                     "ops:tool:gcp-armor:home",
                     "GCP's WAF and DDoS protection. Integrates with Load Balancing."),
            ArchTool("iptables", "iptables / nftables",
                     "https://netfilter.org/projects/nftables/",
                     "ops:tool:iptables:home",
                     "Linux's host firewall. The packet-filtering foundation everything else builds on."),
            ArchTool("ufw", "ufw (Uncomplicated Firewall)",
                     "https://help.ubuntu.com/community/UFW",
                     "ops:tool:ufw:home",
                     "Friendlier wrapper around iptables. The Ubuntu/Debian default for simple host firewall rules."),
            ArchTool("pfsense", "pfSense",
                     "https://www.pfsense.org/",
                     "ops:tool:pfsense:home",
                     "Open-source firewall and router OS. The default for serious on-prem firewalls."),
            ArchTool("opnsense", "OPNsense",
                     "https://opnsense.org/",
                     "ops:tool:opnsense:home",
                     "Fork of pfSense with a different update cadence and license posture."),
            ArchTool("letsencrypt", "Let's Encrypt",
                     "https://letsencrypt.org/",
                     "ops:tool:letsencrypt:home",
                     "Free, automated TLS certificate authority. The reason HTTPS is the default now."),
            ArchTool("linkerd", "Linkerd",
                     "https://linkerd.io/",
                     "ops:tool:linkerd:home",
                     "Service mesh with built-in mTLS. The lightweight alternative to Istio."),
        ),
    ),
]


# ─── SPINE ───────────────────────────────────────────────────────────────────

OPS_SPINE_RESOURCES: list[ArchResource] = [
    _s("Site Reliability Engineering",
       "https://sre.google/sre-book/table-of-contents/",
       "Google · sre.google", "ops:spine:sre-book", "Tutorial",
       "Google's foundational SRE book, free online: SLOs, error budgets, toil, on-call, and postmortems."),
    _s("The Site Reliability Workbook",
       "https://sre.google/workbook/table-of-contents/",
       "Google · sre.google", "ops:spine:sre-workbook", "Tutorial",
       "Practical companion to the SRE book with worked examples for implementing SLOs and incident response."),
    _s("Observability Engineering",
       "https://www.honeycomb.io/observability-engineering-oreilly-book",
       "Majors, Fong-Jones, Miranda · Honeycomb / O'Reilly", "ops:spine:observability-engineering", "Tutorial",
       "Canonical O'Reilly text on events-first observability; free PDF behind a form on Honeycomb."),
    _s("Systems Performance, 2nd Edition",
       "https://www.brendangregg.com/systems-performance-2nd-edition-book.html",
       "Brendan Gregg", "ops:spine:systems-performance", "Tutorial",
       "The definitive deep-dive on Linux performance: CPUs, memory, disks, networks, tracing, and methodology."),
    _s("Performance Analysis Methodology",
       "https://www.brendangregg.com/methodology.html",
       "Brendan Gregg", "ops:spine:gregg-methodology", "Best Practices",
       "USE Method and other systematic approaches to finding real performance bottlenecks fast."),
    _s("Static Stability Using Availability Zones",
       "https://aws.amazon.com/builders-library/static-stability-using-availability-zones/",
       "AWS Builders' Library", "ops:spine:static-stability", "Best Practices",
       "Design so a dependency's failure changes nothing. Pre-provision instead of reacting."),
    _s("Avoiding insurmountable queue backlogs",
       "https://aws.amazon.com/builders-library/avoiding-insurmountable-queue-backlogs/",
       "David Yanacek · AWS Builders' Library", "ops:spine:queue-backlogs", "Best Practices",
       "How Amazon designs queue-based systems that recover from backlogs instead of compounding them."),
    _s("Distributed Systems Observability",
       "https://www.oreilly.com/library/view/distributed-systems-observability/9781492033431/",
       "Cindy Sridharan · O'Reilly", "ops:spine:sridharan-observability", "Tutorial",
       "Short free e-book defining monitoring vs observability and the three pillars: logs, metrics, traces."),
    _s("Friday Deploy Freezes Are Exactly Like Murdering Puppies",
       "https://charity.wtf/2019/05/01/friday-deploy-freezes-are-exactly-like-murdering-puppies/",
       "Charity Majors", "ops:spine:friday-deploys", "Discussion",
       "The case that deploy fear is technical debt; small, frequent, author-owned changes beat blanket freezes."),
    _s("DORA Research 2025",
       "https://dora.dev/research/2025/",
       "DORA · Google Cloud", "ops:spine:dora-2025", "Best Practices",
       "Latest State of DevOps research linking delivery practices, AI, and reliability to org performance."),
    _s("Cultivating Production Excellence",
       "https://www.infoq.com/presentations/complex-distributed-systems/",
       "Liz Fong-Jones · InfoQ", "ops:spine:production-excellence", "Talk",
       "Production excellence as a practice: shared ownership, observability, SLOs, and risk-based prioritization."),
    _s("The Honeycomb Blog",
       "https://www.honeycomb.io/blog",
       "Honeycomb", "ops:spine:honeycomb-blog", "Discussion",
       "Active blog from the observability vendor that practitioners actually read: SLOs, OTel, incidents, on-call."),
]


# ─── PER-TOOL RESOURCES ─────────────────────────────────────────────────────

OPS_TOOL_RESOURCES: list[ArchToolResource] = [
    # Observability
    _r("Prometheus Getting Started",
       "https://prometheus.io/docs/prometheus/latest/getting_started/",
       "Prometheus docs", "ops:res:prometheus:getting-started", ["prometheus"], "Tutorial",
       "Install Prometheus, scrape targets, run PromQL queries, and configure your first alert."),
    _r("PromQL for Mere Mortals",
       "https://grafana.com/blog/2020/02/04/introduction-to-promql-the-prometheus-query-language/",
       "Grafana Labs blog", "ops:res:prometheus:promql-intro", ["prometheus"], "Tutorial",
       "Approachable intro to PromQL data types, selectors, rate, and aggregation operators."),
    _r("Grafana Getting Started",
       "https://grafana.com/docs/grafana/latest/getting-started/",
       "Grafana docs", "ops:res:grafana:getting-started", ["grafana"], "Tutorial",
       "Install Grafana, connect a data source, build dashboards, and configure alerting."),
    _r("OpenTelemetry Getting Started",
       "https://opentelemetry.io/docs/getting-started/",
       "OpenTelemetry docs", "ops:res:opentelemetry:getting-started", ["opentelemetry"], "Tutorial",
       "Instrument an app with traces, metrics, and logs using the Collector and language SDKs."),
    _r("OpenTelemetry Demo",
       "https://opentelemetry.io/docs/demo/",
       "OpenTelemetry docs", "ops:res:opentelemetry:demo", ["opentelemetry"], "Tutorial",
       "Microservices reference app showing real instrumentation across many languages and signals."),
    _r("Grafana Loki Get Started",
       "https://grafana.com/docs/loki/latest/get-started/",
       "Grafana docs", "ops:res:loki:get-started", ["loki"], "Tutorial",
       "Install Loki, ship logs with Promtail or Alloy, and query them with LogQL in Grafana."),
    _r("Grafana Tempo Getting Started",
       "https://grafana.com/docs/tempo/latest/getting-started/",
       "Grafana docs", "ops:res:tempo:getting-started", ["tempo"], "Tutorial",
       "Deploy Tempo, instrument an app, configure a collector, and visualize traces in Grafana."),
    _r("Tempo Quick Start (Docker)",
       "https://grafana.com/docs/tempo/latest/getting-started/docker-example/",
       "Grafana docs", "ops:res:tempo:docker-quickstart", ["tempo"], "Tutorial",
       "Spin up a local Tempo instance via Docker Compose to explore distributed tracing end-to-end."),
    _r("Grafana Mimir Get Started",
       "https://grafana.com/docs/mimir/latest/get-started/",
       "Grafana docs", "ops:res:mimir:get-started", ["mimir"], "Tutorial",
       "Run Mimir in monolithic mode, scrape Prometheus metrics, and query them through Grafana."),
    _r("Grafana Mimir Documentation",
       "https://grafana.com/docs/mimir/latest/",
       "Grafana docs", "ops:res:mimir:docs", ["mimir"], "Best Practices",
       "Architecture, operations, and tenancy patterns for long-term Prometheus storage at scale."),
    _r("Pydantic Logfire Documentation",
       "https://logfire.pydantic.dev/docs/",
       "Pydantic docs", "ops:res:logfire:docs", ["logfire"], "Tutorial",
       "Install Logfire, instrument Python apps, and view structured traces and logs in the UI."),
    _r("Honeycomb Get Started",
       "https://docs.honeycomb.io/get-started/",
       "Honeycomb docs", "ops:res:honeycomb:get-started", ["honeycomb"], "Tutorial",
       "Send events via OpenTelemetry, run BubbleUp queries, and investigate production issues."),
    _r("Getting Started with Datadog APM",
       "https://docs.datadoghq.com/getting_started/tracing/",
       "Datadog docs", "ops:res:datadog:tracing-getting-started", ["datadog"], "Tutorial",
       "Install the Datadog Agent, instrument an app, and explore your first traces."),
    _r("Datadog APM Documentation",
       "https://docs.datadoghq.com/tracing/",
       "Datadog docs", "ops:res:datadog:apm-docs", ["datadog"], "Best Practices",
       "APM landing page: instrumentation, configuration, and trace correlation for production workloads."),
    _r("Getting Started with Sentry",
       "https://docs.sentry.io/product/sentry-basics/",
       "Sentry docs", "ops:res:sentry:basics", ["sentry"], "Tutorial",
       "SDK install, DSN configuration, and verification across backend languages and frameworks."),
    _r("Sentry Documentation",
       "https://docs.sentry.io/",
       "Sentry docs", "ops:res:sentry:docs", ["sentry"], "Best Practices",
       "Docs root covering error tracking, performance, profiling, alerts, and release health."),
    _r("Get Started with New Relic",
       "https://docs.newrelic.com/docs/new-relic-solutions/get-started/intro-new-relic/",
       "New Relic docs", "ops:res:new-relic:get-started", ["new-relic"], "Tutorial",
       "Introductory tour of APM, infrastructure, browser, and alerting flows with quick install paths."),
    _r("Introduction to New Relic APM",
       "https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/introduction-apm/",
       "New Relic docs", "ops:res:new-relic:apm-intro", ["new-relic"], "Tutorial",
       "Language-agent install guides plus the core APM concepts for instrumenting a production service."),
    _r("Better Stack: Observability Guide",
       "https://betterstack.com/community/guides/observability/",
       "Better Stack docs", "ops:res:better-stack:observability-guide", ["better-stack"], "Best Practices",
       "Vendor-maintained primer on metrics, traces, logs, dashboards, and alerting strategies."),
    _r("Distributed Tracing with Better Stack",
       "https://betterstack.com/docs/logs/tracing/",
       "Better Stack docs", "ops:res:better-stack:tracing", ["better-stack"], "Tutorial",
       "Send OTLP traces into Better Stack using the collector or OpenTelemetry directly."),
    _r("Axiom Docs",
       "https://axiom.co/docs/introduction",
       "Axiom docs", "ops:res:axiom:introduction", ["axiom"], "Best Practices",
       "Introduction to Axiom's EventDB and MetricsDB platform for telemetry at scale."),
    _r("Get Started with SigNoz",
       "https://signoz.io/docs/install/",
       "SigNoz docs", "ops:res:signoz:install", ["signoz"], "Tutorial",
       "Install SigNoz via cloud, Docker Compose, or Kubernetes Helm to start ingesting OTLP signals."),
    _r("Introduction to SigNoz",
       "https://signoz.io/docs/introduction/",
       "SigNoz docs", "ops:res:signoz:introduction", ["signoz"], "Best Practices",
       "Overview of SigNoz's open-source logs, traces, and metrics on OpenTelemetry."),

    # Incident response & alerting
    _r("PagerDuty Knowledge Base",
       "https://support.pagerduty.com/main/docs/introduction",
       "PagerDuty docs", "ops:res:pagerduty:kb-intro", ["pagerduty"], "Best Practices",
       "Official knowledge-base entry point with onboarding training and configuration guidance."),
    _r("PagerDuty Incident Response: Getting Started",
       "https://response.pagerduty.com/getting_started/",
       "PagerDuty Incident Response", "ops:res:pagerduty:incident-response", ["pagerduty"], "Best Practices",
       "PagerDuty's open documentation on building an incident response practice, including roles and process."),
    _r("Opsgenie Quickstart Guide",
       "https://support.atlassian.com/opsgenie/docs/read-opsgenies-quickstart-guide/",
       "Atlassian docs", "ops:res:opsgenie:quickstart", ["opsgenie"], "Tutorial",
       "Configure profile, notification rules, schedules, and integrations to start receiving alerts."),
    _r("Learn How Opsgenie Works",
       "https://support.atlassian.com/opsgenie/docs/learn-how-opsgenie-works/",
       "Atlassian docs", "ops:res:opsgenie:how-it-works", ["opsgenie"], "Best Practices",
       "Mental model for teams, schedules, escalations, and routing rules in Opsgenie."),
    _r("Get Started with Grafana OnCall",
       "https://grafana.com/docs/oncall/latest/set-up/get-started/",
       "Grafana docs", "ops:res:grafana-oncall:get-started", ["grafana-oncall"], "Tutorial",
       "Stand up OnCall, wire integrations, define notification policies, and connect Slack."),
    _r("Grafana OnCall Documentation",
       "https://grafana.com/docs/oncall/latest/",
       "Grafana docs", "ops:res:grafana-oncall:docs", ["grafana-oncall"], "Best Practices",
       "Reference for OnCall scheduling, escalations, integrations, and notification policies."),
    _r("FireHydrant Onboarding Quickstart",
       "https://firehydrant.com/docs/getting-started/configuration-quick-start-guide",
       "FireHydrant docs", "ops:res:firehydrant:quickstart", ["firehydrant"], "Tutorial",
       "Walks first-time admins through the integrations and configuration needed before the first incident."),
    _r("FireHydrant Documentation",
       "https://docs.firehydrant.com/",
       "FireHydrant docs", "ops:res:firehydrant:docs", ["firehydrant"], "Best Practices",
       "Full docs covering Signals alerting, incident lifecycle, catalog, and runbooks."),
    _r("incident.io Help Center",
       "https://docs.incident.io/",
       "incident.io docs", "ops:res:incident-io:docs", ["incident-io"], "Best Practices",
       "Searchable docs for On-call, Response, Status Pages, Catalog, Workflows, and Insights."),
    _r("Get Started with Statuspage",
       "https://support.atlassian.com/statuspage/docs/get-started-with-statuspage/",
       "Atlassian docs", "ops:res:statuspage:get-started", ["statuspage"], "Tutorial",
       "Configure components, subscriber channels, and your first incident communication."),
    _r("Statuspage: Launch Your Status Page",
       "https://support.atlassian.com/statuspage/docs/launch-your-status-page/",
       "Atlassian docs", "ops:res:statuspage:launch", ["statuspage"], "Best Practices",
       "Pre-launch checklist covering branding, components, automation, and subscriber setup."),
    _r("Better Stack: Get Started with Incidents",
       "https://betterstack.com/docs/uptime/working-with-incidents/",
       "Better Stack docs", "ops:res:better-stack-incident:get-started", ["better-stack-incident"], "Tutorial",
       "Create incidents from monitors, manually, or via API; resolve, group, and post-mortem them."),
    _r("Better Stack Incident Management",
       "https://betterstack.com/incident-management",
       "Better Stack docs", "ops:res:better-stack-incident:overview", ["better-stack-incident"], "Best Practices",
       "Product overview tying on-call schedules, Slack workflows, and status pages into one offering."),

    # Logging pipelines
    _r("Vector Quickstart",
       "https://vector.dev/docs/setup/quickstart/",
       "Vector docs", "ops:res:vector:quickstart", ["vector"], "Tutorial",
       "Install Vector and build your first sources to transforms to sinks observability pipeline."),
    _r("Vector Documentation",
       "https://vector.dev/docs/",
       "Vector docs", "ops:res:vector:docs", ["vector"], "Best Practices",
       "Reference for every Vector component, plus operating-at-scale guidance."),
    _r("Get Started with Fluent Bit",
       "https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit",
       "Fluent Bit docs", "ops:res:fluent-bit:getting-started", ["fluent-bit"], "Tutorial",
       "Install Fluent Bit on Linux, macOS, Windows, or BSD and ship your first pipeline."),
    _r("Fluent Bit Manual",
       "https://docs.fluentbit.io/manual",
       "Fluent Bit docs", "ops:res:fluent-bit:manual", ["fluent-bit"], "Best Practices",
       "Inputs, parsers, filters, outputs, and operating Fluent Bit in production."),
    _r("Fluentd Quickstart",
       "https://docs.fluentd.org/quickstart",
       "Fluentd docs", "ops:res:fluentd:quickstart", ["fluentd"], "Tutorial",
       "Installation, configuration, and the basic log forwarder pattern with Fluentd."),
    _r("Fluentd Documentation",
       "https://docs.fluentd.org/",
       "Fluentd docs", "ops:res:fluentd:docs", ["fluentd"], "Best Practices",
       "Plugin, deployment, and tuning guides for Fluentd in production."),
    _r("Bento Getting Started",
       "https://warpstreamlabs.github.io/bento/docs/guides/getting_started/",
       "Bento docs", "ops:res:bento:getting-started", ["bento"], "Tutorial",
       "Install Bento (the WarpStream-maintained Benthos fork) and run your first stream-processing config."),
    _r("What is Bento For?",
       "https://warpstreamlabs.github.io/bento/docs/about/",
       "Bento docs", "ops:res:bento:about", ["bento"], "Best Practices",
       "Conceptual intro to Bento's declarative, at-least-once stream processing pipelines."),
    _r("Get Started with Cribl Stream",
       "https://docs.cribl.io/stream/getting-started-guide/",
       "Cribl docs", "ops:res:cribl:get-started", ["cribl"], "Tutorial",
       "One-hour hands-on tour of Sources, Routes, Pipelines, Functions, and Destinations."),
    _r("Cribl Stream Documentation",
       "https://docs.cribl.io/stream/",
       "Cribl docs", "ops:res:cribl:docs", ["cribl"], "Best Practices",
       "Documentation root for Cribl Stream covering deployment, processing, and routing."),

    # Performance & profiling
    _r("Get Started with Pyroscope",
       "https://grafana.com/docs/pyroscope/latest/get-started/",
       "Grafana docs", "ops:res:pyroscope:get-started", ["pyroscope"], "Tutorial",
       "Run Pyroscope, instrument your app with an SDK or Alloy, and explore flame graphs in Grafana."),
    _r("Pyroscope Ride-Share Tutorial",
       "https://grafana.com/docs/pyroscope/latest/get-started/ride-share-tutorial/",
       "Grafana docs", "ops:res:pyroscope:ride-share", ["pyroscope"], "Tutorial",
       "Hands-on demo app that walks through diagnosing CPU and memory issues with continuous profiling."),
    _r("Parca Overview",
       "https://www.parca.dev/docs/overview/",
       "Parca docs", "ops:res:parca:overview", ["parca"], "Best Practices",
       "Intro to Parca's server plus eBPF agent architecture for always-on continuous profiling."),
    _r("Polar Signals Overview",
       "https://www.polarsignals.com/docs/overview",
       "Polar Signals docs", "ops:res:polar-signals:overview", ["polar-signals"], "Best Practices",
       "How Polar Signals Cloud combines a zero-instrumentation eBPF agent with hosted symbolization."),
    _r("Polar Signals Agent Deployment Guide",
       "https://www.polarsignals.com/docs/agent-deployment-guide",
       "Polar Signals docs", "ops:res:polar-signals:agent", ["polar-signals"], "Tutorial",
       "Deploy the Polar Signals agent and stream profiles into Polar Signals Cloud."),
    _r("Pixie Overview",
       "https://docs.px.dev/about-pixie/what-is-pixie/",
       "Pixie docs", "ops:res:pixie:overview", ["pixie"], "Best Practices",
       "How Pixie uses eBPF for auto-telemetry on Kubernetes without manual instrumentation."),
    _r("Getting Started with Datadog Continuous Profiler",
       "https://docs.datadoghq.com/getting_started/profiler/",
       "Datadog docs", "ops:res:datadog-profiler:get-started", ["datadog-profiler"], "Tutorial",
       "Profile a sample service, find a real performance problem, and fix it with the Datadog Profiler."),
    _r("Datadog Continuous Profiler",
       "https://docs.datadoghq.com/profiler/",
       "Datadog docs", "ops:res:datadog-profiler:docs", ["datadog-profiler"], "Best Practices",
       "Reference docs for enabling, configuring, and interpreting profile data across runtimes."),
    _r("Flame Graphs",
       "https://www.brendangregg.com/flamegraphs.html",
       "Brendan Gregg", "ops:res:perf-flamegraph:gregg-page", ["perf-flamegraph"], "Best Practices",
       "Brendan Gregg's canonical page introducing flame graphs, types, and how to read them."),
    _r("FlameGraph Toolchain",
       "https://github.com/brendangregg/FlameGraph",
       "GitHub", "ops:res:perf-flamegraph:github", ["perf-flamegraph"], "Tutorial",
       "The official flamegraph.pl toolchain with stack-collapse scripts for perf, DTrace, and friends."),
    _r("bpftrace One-Liner Tutorial",
       "https://bpftrace.org/tutorial-one-liners",
       "bpftrace docs", "ops:res:bpftrace:one-liners", ["bpftrace"], "Tutorial",
       "Learn bpftrace in 12 lessons through one-liners covering probes, maps, and printf actions."),
    _r("bpftrace Project Home",
       "https://bpftrace.org/",
       "bpftrace docs", "ops:res:bpftrace:home", ["bpftrace"], "Best Practices",
       "Reference docs, language guides, and labs for dynamic Linux tracing with bpftrace."),

    # Identity & auth
    _r("Auth0 Get Started",
       "https://auth0.com/docs/get-started",
       "Auth0 docs", "ops:res:auth0:get-started", ["auth0"], "Tutorial",
       "Set up a tenant, create applications, and integrate login via Universal Login and SDKs."),
    _r("Auth0 Architecture Scenarios",
       "https://auth0.com/docs/get-started/architecture-scenarios",
       "Auth0 docs", "ops:res:auth0:architecture-scenarios", ["auth0"], "Best Practices",
       "Reference architectures for SPA+API, mobile+API, and B2B/B2C identity scenarios."),
    _r("Clerk Quickstarts",
       "https://clerk.com/docs/getting-started/quickstart/overview",
       "Clerk docs", "ops:res:clerk:quickstarts", ["clerk"], "Tutorial",
       "Framework-specific quickstarts (Next.js, React, Express, etc.) for adding Clerk auth in minutes."),
    _r("Clerk Documentation",
       "https://clerk.com/docs",
       "Clerk docs", "ops:res:clerk:docs", ["clerk"], "Best Practices",
       "Docs root covering auth strategies, components, organizations, billing, and deployment."),
    _r("Get Started with WorkOS AuthKit",
       "https://workos.com/docs/authkit",
       "WorkOS docs", "ops:res:workos:authkit", ["workos"], "Tutorial",
       "Add a hosted auth flow with SSO, social login, and passkeys in under ten minutes."),
    _r("WorkOS Documentation",
       "https://workos.com/docs",
       "WorkOS docs", "ops:res:workos:docs", ["workos"], "Best Practices",
       "Enterprise-ready auth APIs: SSO, SCIM directory sync, audit logs, user management."),
    _r("Stytch Get Started",
       "https://stytch.com/docs/get-started/overview",
       "Stytch docs", "ops:res:stytch:get-started", ["stytch"], "Tutorial",
       "Overview of B2B and Consumer auth suites plus framework-specific quickstart paths."),
    _r("Stytch API Reference",
       "https://stytch.com/docs/api",
       "Stytch docs", "ops:res:stytch:api", ["stytch"], "Best Practices",
       "Full API reference covering magic links, OTP, OAuth, sessions, and fraud detection."),
    _r("Keycloak Getting Started (Docker)",
       "https://www.keycloak.org/getting-started/getting-started-docker",
       "Keycloak docs", "ops:res:keycloak:docker-start", ["keycloak"], "Tutorial",
       "Run Keycloak in Docker, create a realm, register a client, and secure a sample app."),
    _r("Keycloak Server Administration Guide",
       "https://www.keycloak.org/docs/latest/server_admin/",
       "Keycloak docs", "ops:res:keycloak:server-admin", ["keycloak"], "Best Practices",
       "Reference for realms, clients, identity brokering, user federation, and authentication flows."),
    _r("Ory Documentation",
       "https://www.ory.sh/docs/",
       "Ory docs", "ops:res:ory:docs", ["ory"], "Tutorial",
       "Get started with Ory Kratos identities, Hydra OAuth2/OIDC, Keto permissions, and Oathkeeper."),
    _r("SuperTokens Documentation",
       "https://supertokens.com/docs",
       "SuperTokens docs", "ops:res:supertokens:docs", ["supertokens"], "Tutorial",
       "CLI-based quickstart for integrating SuperTokens SDKs across common backend and frontend stacks."),
    _r("SuperTokens Authentication Overview",
       "https://supertokens.com/docs/authentication/overview",
       "SuperTokens docs", "ops:res:supertokens:auth-overview", ["supertokens"], "Best Practices",
       "Authentication recipes: email/password, passwordless, social/enterprise SSO, and MFA."),
    _r("FusionAuth Get Started",
       "https://fusionauth.io/docs/get-started/",
       "FusionAuth docs", "ops:res:fusionauth:get-started", ["fusionauth"], "Tutorial",
       "Pick a 15-minute quickstart for your language or framework and stand up FusionAuth CIAM."),
    _r("FusionAuth Documentation",
       "https://fusionauth.io/docs/",
       "FusionAuth docs", "ops:res:fusionauth:docs", ["fusionauth"], "Best Practices",
       "Install, identity providers, MFA, passkeys, and APIs reference."),
    _r("Logto Introduction",
       "https://docs.logto.io/introduction",
       "Logto docs", "ops:res:logto:introduction", ["logto"], "Best Practices",
       "Logto identity-and-access overview: SSO, MFA, RBAC, multi-tenancy on OIDC and OAuth 2.1."),
    _r("Logto Quick Starts",
       "https://docs.logto.io/quick-starts/python",
       "Logto docs", "ops:res:logto:quick-starts", ["logto"], "Tutorial",
       "Framework quickstarts (Python shown; 30+ SDKs available) for adding Logto auth to an app."),

    # Secrets management
    _r("Vault Tutorials",
       "https://developer.hashicorp.com/vault/tutorials",
       "HashiCorp Developer", "ops:res:vault:tutorials", ["vault"], "Tutorial",
       "Hands-on tutorials for KV secrets, dynamic database creds, transit encryption, and auth methods."),
    _r("Vault Production Hardening",
       "https://developer.hashicorp.com/vault/tutorials/operations/production-hardening",
       "HashiCorp Developer", "ops:res:vault:production-hardening", ["vault"], "Best Practices",
       "Official checklist: end-to-end TLS, root token rotation, auditing, and least-privilege policies."),
    _r("What Is AWS Secrets Manager?",
       "https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html",
       "AWS docs", "ops:res:aws-secrets-manager:intro", ["aws-secrets-manager"], "Best Practices",
       "Conceptual intro plus links into setup, retrieval, and rotation patterns."),
    _r("AWS Secrets Manager Tutorials",
       "https://docs.aws.amazon.com/secretsmanager/latest/userguide/tutorials.html",
       "AWS docs", "ops:res:aws-secrets-manager:tutorials", ["aws-secrets-manager"], "Tutorial",
       "Hands-on tutorials covering moving hardcoded secrets, configuring rotation, and CodeGuru integration."),
    _r("GCP Secret Manager Quickstart",
       "https://docs.cloud.google.com/secret-manager/docs/create-secret-quickstart",
       "Google Cloud docs", "ops:res:gcp-secret-manager:quickstart", ["gcp-secret-manager"], "Tutorial",
       "Create, access, and rotate a secret via console, gcloud, or client library."),
    _r("GCP Secret Manager Documentation",
       "https://docs.cloud.google.com/secret-manager/docs",
       "Google Cloud docs", "ops:res:gcp-secret-manager:docs", ["gcp-secret-manager"], "Best Practices",
       "Concepts, IAM, regional configs, and integration patterns for Secret Manager."),
    _r("1Password Secrets Automation",
       "https://developer.1password.com/docs/secrets-automation/",
       "1Password Developer", "ops:res:1password-secrets:automation", ["1password-secrets"], "Best Practices",
       "Overview of Service Accounts and Connect server approaches to automating secret retrieval."),
    _r("Get Started with 1Password Service Accounts",
       "https://developer.1password.com/docs/service-accounts/get-started/",
       "1Password Developer", "ops:res:1password-secrets:service-accounts", ["1password-secrets"], "Tutorial",
       "Create a service account, scope its vaults, and authenticate the 1Password CLI in CI/CD."),
    _r("Getting Started with Doppler",
       "https://docs.doppler.com/docs/getting-started",
       "Doppler docs", "ops:res:doppler:getting-started", ["doppler"], "Tutorial",
       "Project and config setup, then sync secrets to local apps, cloud providers, and other stores."),
    _r("Doppler Documentation",
       "https://docs.doppler.com/",
       "Doppler docs", "ops:res:doppler:docs", ["doppler"], "Best Practices",
       "SecretOps workflows, RBAC, audit logs, and integrations."),
    _r("What is Infisical?",
       "https://infisical.com/docs/documentation/getting-started/introduction",
       "Infisical docs", "ops:res:infisical:introduction", ["infisical"], "Tutorial",
       "Sign up for Infisical Cloud or self-host, then manage secrets, certs, and access across environments."),
    _r("Infisical Secrets Management",
       "https://infisical.com/docs/documentation/platform/secrets-mgmt/overview",
       "Infisical docs", "ops:res:infisical:secrets-mgmt", ["infisical"], "Best Practices",
       "Platform overview for secrets storage, rotation, references, and audit logging."),
    _r("SOPS: Secrets OPerationS",
       "https://getsops.io/",
       "getsops.io", "ops:res:sops:home", ["sops"], "Best Practices",
       "CNCF-hosted project site for the editor that encrypts values inside YAML/JSON/ENV/INI files."),
    _r("SOPS on GitHub",
       "https://github.com/getsops/sops",
       "GitHub", "ops:res:sops:github", ["sops"], "Tutorial",
       "README with install and usage walkthroughs for SOPS with KMS, age, PGP, and Vault backends."),
    _r("age File Encryption",
       "https://github.com/FiloSottile/age",
       "GitHub", "ops:res:age:github", ["age"], "Tutorial",
       "Official repo and README for age, a simple modern file-encryption tool with small explicit keys."),

    # Network security & firewalls
    _r("Cloudflare WAF: Get Started",
       "https://developers.cloudflare.com/waf/get-started/",
       "Cloudflare docs", "ops:res:cloudflare-waf:get-started", ["cloudflare-waf"], "Tutorial",
       "Enable Cloudflare's Managed Rulesets and OWASP Core Ruleset, tune paranoia and score thresholds."),
    _r("Cloudflare WAF Overview",
       "https://developers.cloudflare.com/waf/",
       "Cloudflare docs", "ops:res:cloudflare-waf:overview", ["cloudflare-waf"], "Best Practices",
       "Custom rules, rate limiting, exposed credentials, and bot rules."),
    _r("Get Started with AWS WAF",
       "https://docs.aws.amazon.com/waf/latest/developerguide/getting-started.html",
       "AWS docs", "ops:res:aws-waf:get-started", ["aws-waf"], "Tutorial",
       "Build your first Web ACL, attach managed rule groups, and protect a CloudFront or ALB resource."),
    _r("AWS WAF Developer Guide",
       "https://docs.aws.amazon.com/waf/",
       "AWS docs", "ops:res:aws-waf:docs", ["aws-waf"], "Best Practices",
       "Rules, rule groups, Firewall Manager, and Shield Advanced reference."),
    _r("Cloud Armor Product Overview",
       "https://docs.cloud.google.com/armor/docs/cloud-armor-overview",
       "Google Cloud docs", "ops:res:gcp-armor:overview", ["gcp-armor"], "Best Practices",
       "Conceptual intro to Cloud Armor security policies, preconfigured WAF rules, and load-balancer attach points."),
    _r("Configure Cloud Armor Security Policies",
       "https://docs.cloud.google.com/armor/docs/configure-security-policies",
       "Google Cloud docs", "ops:res:gcp-armor:configure", ["gcp-armor"], "Tutorial",
       "Create a security policy, add prioritized rules, and attach it to a backend service."),
    _r("nftables in 10 Minutes",
       "https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes",
       "nftables wiki", "ops:res:iptables:nftables-quickref", ["iptables"], "Tutorial",
       "Upstream wiki primer on tables, chains, rules, and families; the successor to iptables."),
    _r("nftables Wiki",
       "https://wiki.nftables.org/wiki-nftables/index.php/Main_Page",
       "nftables wiki", "ops:res:iptables:nftables-wiki", ["iptables"], "Best Practices",
       "Examples, migration-from-iptables guides, and command reference."),
    _r("UFW Community Help Wiki",
       "https://help.ubuntu.com/community/UFW",
       "Ubuntu wiki", "ops:res:ufw:wiki", ["ufw"], "Tutorial",
       "Official Ubuntu community wiki on enabling, configuring, and logging the Uncomplicated Firewall."),
    _r("Ubuntu Server: Firewalls",
       "https://documentation.ubuntu.com/server/how-to/security/firewalls/",
       "Ubuntu docs", "ops:res:ufw:server-docs", ["ufw"], "Best Practices",
       "Canonical's server-docs section on configuring host firewalls with UFW."),
    _r("pfSense Getting Started",
       "https://www.pfsense.org/getting-started/",
       "pfSense", "ops:res:pfsense:getting-started", ["pfsense"], "Tutorial",
       "Project landing page linking to install media, the docs portal, and configuration walkthroughs."),
    _r("pfSense Documentation",
       "https://docs.netgate.com/pfsense/en/latest/",
       "Netgate docs", "ops:res:pfsense:docs", ["pfsense"], "Best Practices",
       "Netgate-maintained pfSense manual covering install, networking, VPN, and high availability."),
    _r("OPNsense Quickstart",
       "https://docs.opnsense.org/hardware/quickstart.html",
       "OPNsense docs", "ops:res:opnsense:quickstart", ["opnsense"], "Tutorial",
       "Hardware selection, install media, and first-boot configuration for OPNsense."),
    _r("OPNsense Documentation",
       "https://docs.opnsense.org/index.html",
       "OPNsense docs", "ops:res:opnsense:docs", ["opnsense"], "Best Practices",
       "Install, manual configuration, and the development manual."),
    _r("Let's Encrypt: Getting Started",
       "https://letsencrypt.org/getting-started/",
       "Let's Encrypt", "ops:res:letsencrypt:getting-started", ["letsencrypt"], "Tutorial",
       "Decide between provider-managed and self-managed ACME flows, with Certbot recommended for self-managed."),
    _r("Let's Encrypt Documentation",
       "https://letsencrypt.org/docs/",
       "Let's Encrypt", "ops:res:letsencrypt:docs", ["letsencrypt"], "Best Practices",
       "Rate limits, challenge types, ACME clients, and best practices."),
    _r("Linkerd Getting Started",
       "https://linkerd.io/2.13/getting-started/",
       "Linkerd docs", "ops:res:linkerd:getting-started", ["linkerd"], "Tutorial",
       "Install the CLI, deploy the control plane to Kubernetes, and mesh your first application."),
    _r("Linkerd Overview",
       "https://linkerd.io/2-edge/overview/",
       "Linkerd docs", "ops:res:linkerd:overview", ["linkerd"], "Best Practices",
       "Conceptual overview of Linkerd's Rust-based service-mesh data plane and control plane."),
]


# ─── CREATORS ────────────────────────────────────────────────────────────────

OPS_PEOPLE: list[Person] = [
    Person(
        "Brendan Gregg", "brendangregg", "blog", "https://www.brendangregg.com/",
        "ops:person:blog:brendangregg",
        "The reference for Linux performance, flame graphs, and BPF observability.",
    ),
    Person(
        "Charity Majors", "mipsytipsy", "blog", "https://charity.wtf/",
        "ops:person:blog:charity",
        "Honeycomb co-founder. Defines what modern observability means and where it's going.",
    ),
    Person(
        "Jessica Kerr", "jessitron", "blog", "https://jessitron.com/",
        "ops:person:blog:jessitron",
        "Honeycomb dev advocate; systems-thinking essays on observability and socio-technical design.",
    ),
    Person(
        "Cindy Sridharan", "copyconstruct", "blog", "https://copyconstruct.medium.com/",
        "ops:person:blog:copyconstruct",
        "Distributed systems and observability writing; essays on testing in production and reliability.",
    ),
    Person(
        "Liz Fong-Jones", "lizthegrey", "x", "https://x.com/lizthegrey",
        "ops:person:x:liz-fong-jones",
        "Honeycomb principal developer advocate. SRE practice and production-excellence framework.",
    ),
    Person(
        "John Allspaw", "allspaw", "blog", "https://www.adaptivecapacitylabs.com/blog/",
        "ops:person:blog:allspaw",
        "Adaptive Capacity Labs; canonical voice on incident analysis and learning from failure.",
    ),
    Person(
        "Lorin Hochstein", "norootcause", "blog", "https://surfingcomplexity.blog/",
        "ops:person:blog:lorin-hochstein",
        "Netflix SRE alum; chaos engineering, postmortem culture, and resilience engineering.",
    ),
    Person(
        "Casey Rosenthal", "caseyrosenthal", "blog", "https://www.verica.io/blog/",
        "ops:person:blog:casey-rosenthal",
        "Formerly Netflix Chaos team; co-author of the canonical chaos engineering book.",
    ),
    Person(
        "Kelly Shortridge", "swagitda_", "blog", "https://kellyshortridge.com/",
        "ops:person:blog:kelly-shortridge",
        "Security chaos engineering; author of the canonical book of the same name.",
    ),
    Person(
        "Will Larson", "lethain", "blog", "https://lethain.com/",
        "ops:person:blog:lethain",
        "Engineering leader writing concrete frameworks for ops strategy, on-call, and platform investment.",
    ),
]


# ─── FAQs ────────────────────────────────────────────────────────────────────

OPS_FAQS: list[FAQ] = [
    FAQ(
        "What's the smallest observability stack that's actually useful?",
        "One signal you'll actually look at, instrumented well, beats four "
        "signals you glance at during incidents. Charity Majors frames "
        "this as observability 1.0 vs. 2.0: the three pillars (metrics, "
        "logs, traces) are 1.0. Structured wide events you can slice "
        "arbitrarily are 2.0. For most teams, OpenTelemetry to instrument "
        "plus one backend that handles high-cardinality (Honeycomb, "
        "Logfire) is the smallest setup that pays off. Add the other "
        "pillars once you're actually using the first one.",
        source_label="Charity Majors: Observability 1.0 vs 2.0",
        source_url="https://www.honeycomb.io/blog/one-key-difference-observability1dot0-2dot0",
        source_key="ops:faq:charity-observability-2",
    ),
    FAQ(
        "How do I think about reliability without overengineering?",
        "Static stability is the cleanest mental model: design so that "
        "when a dependency fails, your system behaves the same. "
        "Pre-provision instead of reacting. Pre-build instead of pulling "
        "at request time. Decide what works looks like when half your "
        "dependencies are down. Most overengineering is reacting to "
        "abstract failures instead of ones that have actually hurt you. "
        "Re-read your last three postmortems, then design for those.",
        source_label="AWS Builders' Library: Static Stability",
        source_url="https://aws.amazon.com/builders-library/static-stability-using-availability-zones/",
        source_key="ops:faq:aws-static-stability",
    ),
    FAQ(
        "How do I think about SLOs without overcomplicating them?",
        "Start with one SLO on the one user-facing thing you'd be paged "
        "for: requests successful within some latency budget. Pick a "
        "target you'd actually defend in a meeting (99% is fine; 99.99% "
        "is a research project), and burn-rate alerts that page you "
        "before the budget runs out, not after. The Google SRE Workbook "
        "is still the canonical step-by-step. Skip the elaborate "
        "multi-SLO error-budget machinery until you have one SLO running "
        "for six months.",
        source_label="Google SRE Workbook: Implementing SLOs",
        source_url="https://sre.google/workbook/implementing-slos/",
        source_key="ops:faq:google-slo-workbook",
    ),
    FAQ(
        "Do I need a real incident management tool, or is Slack enough?",
        "Slack is enough until your team is big enough that the absence "
        "of structure costs more than the cost of the tool. Concretely: "
        "when you have multiple concurrent incidents, a postmortem "
        "backlog that's not getting written, or new on-call engineers "
        "asking \"what do I do first?\", Slack alone isn't covering you. "
        "Incident.io and FireHydrant give you channel orchestration, "
        "role tracking, and a clean handoff to the postmortem. The cost "
        "is per-responder pricing; the value is consistency.",
        source_label="Incident.io: The case for incident management software",
        source_url="https://incident.io/blog",
        source_key="ops:faq:incident-mgmt-tool",
    ),
    FAQ(
        "When does my team need a formal on-call rotation?",
        "When the alternative is one person fielding every page, or "
        "nobody fielding pages at night. Both happen earlier than teams "
        "admit. A formal rotation buys predictable handoffs, escalation, "
        "and a clear answer to \"who's the primary?\" — but it only "
        "works if there's a real runbook for the common pages and a "
        "review of what's actually paging you. The cost of a bad "
        "rotation (alert fatigue, burnout) is higher than the cost of "
        "no rotation. Build the page-quality discipline first.",
        source_label="PagerDuty: Setting up your first on-call rotation",
        source_url="https://www.pagerduty.com/resources/learn/call-rotations-schedules/",
        source_key="ops:faq:on-call-rotation",
    ),
    FAQ(
        "Should I outsource auth, or roll my own?",
        "Outsource. Auth is one of the highest blast-radius things you'll "
        "ever ship, and the cost of getting it wrong is everyone else's "
        "data. The strongest argument for rolling your own is when your "
        "domain model genuinely needs identity primitives the vendors "
        "don't offer (rare). For most teams, Auth0 / Clerk / WorkOS / "
        "Stytch are worth the price; Keycloak / Ory / Supertokens are "
        "the self-hostable middle ground if you want OSS without writing "
        "your own.",
        source_label="Reflag: Why we use Clerk for auth",
        source_url="https://reflag.com/blog/clerk",
        source_key="ops:faq:outsource-auth",
    ),
    FAQ(
        "How do I run a blameless postmortem that doesn't devolve into blame?",
        "Blameless doesn't mean accountability-free. It means the goal "
        "is learning, not punishment, and the operator's actions made "
        "sense given what they knew at the time. Three habits: write "
        "the timeline before the meeting; ask \"how did this make sense to do, in the moment?\" instead of \"who did this?\"; and end "
        "with concrete, owned action items that target the system, not "
        "the operator. John Allspaw's writing is the canonical reference.",
        source_label="John Allspaw: Blameless PostMortems and a Just Culture",
        source_url="https://www.etsy.com/codeascraft/blameless-postmortems",
        source_key="ops:faq:blameless-postmortems",
    ),
]
