"""Post a bot-written announcement to a Discord channel.

The message is generated by the chat bot itself — same persona and same
currently configured model (``CHAT_AGENT_MODEL``) as the live chat agent —
then posted over the bot-token REST API. Operator gives the brief; the bot
writes the copy.

Usage:
    uv run python scripts/announce.py "what to announce" [--channel ID] [--dry-run]

Needs DISCORD_BOT_TOKEN plus the model's API key (GEMINI_API_KEY or
OPENAI_API_KEY) in the environment or .env.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path

import dotenv

sys.path.insert(0, str(Path(__file__).parent.parent))

ANNOUNCEMENTS_CHANNEL_ID = "670004266320134185"

ANNOUNCEMENT_INSTRUCTIONS = """
# Task

You're posting a one-off announcement to the server, not replying in a
conversation. The operator's brief describes what to announce; turn it into
a single Discord message in your own voice.

Rules:
- One message, under 1900 characters, plain Discord markdown.
- Cover every fact in the brief accurately — don't invent details,
  numbers, or dates that aren't in it.
- No @everyone/@here or role pings unless the brief explicitly asks.
- Output ONLY the message text, nothing else.
"""


def _persona() -> str:
    """The chat agent's persona — the prompt intro before turn mechanics."""
    prompt_path = (
        Path(__file__).parent.parent
        / "smarter_dev"
        / "bot"
        / "agents"
        / "prompts"
        / "chat_agent.md"
    )
    text = prompt_path.read_text(encoding="utf-8")
    return text.split("# Your input")[0].strip()


async def generate(brief: str) -> str:
    from pydantic_ai import Agent

    from smarter_dev.bot.agents.chat_agent import _build_model, _model_settings

    agent = Agent(
        _build_model(),
        output_type=str,
        system_prompt=_persona() + "\n" + ANNOUNCEMENT_INSTRUCTIONS,
        model_settings=_model_settings(),
    )
    result = await agent.run(brief)
    return result.output.strip()


async def post(channel_id: str, content: str) -> str:
    from smarter_dev.web.handler_emitter import DiscordEmitter

    token = os.getenv("DISCORD_BOT_TOKEN") or dotenv.get_key(".env", "DISCORD_BOT_TOKEN")
    if not token:
        raise SystemExit("DISCORD_BOT_TOKEN not set (env or .env)")
    emitter = DiscordEmitter(bot_token=token)
    return await emitter.create_message(channel_id, content)


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("brief", help="what the announcement should say")
    parser.add_argument("--channel", default=ANNOUNCEMENTS_CHANNEL_ID)
    parser.add_argument(
        "--dry-run", action="store_true", help="generate and print without posting"
    )
    args = parser.parse_args()

    dotenv.load_dotenv()
    message = await generate(args.brief)
    print(f"--- generated ({len(message)} chars) ---\n{message}\n---")
    if args.dry_run:
        return
    message_id = await post(args.channel, message)
    print(f"posted to channel {args.channel} as message {message_id}")


if __name__ == "__main__":
    asyncio.run(main())
